"""ASTU 2026 2nd Round Model Exit Exam — question bank."""

from __future__ import annotations

FOCUS_GUIDE: dict[str, str] = {
    "C++": "Syntax, pointers, references, memory, file I/O, operators, control flow.",
    "Data Structures": "Stacks, queues, trees, arrays, graphs, recursion, complexity.",
    "Java / OOP": "Encapsulation, abstraction, inheritance, polymorphism, IDE tools.",
    "Web Development": "HTML, CSS, JavaScript, PWA, MVC, web servers, dynamic sites.",
    "Android": "Manifest, components, fragments, threading, resources, broadcast receivers.",
    "Database": "SQL DML, normalization, keys, cardinality, referential integrity.",
    "Operating Systems": "Scheduling, paging, threads, processes, security, deadlock.",
    "Software Engineering": "SDLC models, CASE tools, incremental development, RAD.",
    "Requirements Engineering": "Elicitation, SRS, scope, stakeholder bridge, analysis phase.",
    "Software Architecture": "Architecture docs, quality attributes, abstraction levels, scalability.",
    "Project Management": "PERT, Scrum, CMMI, maintenance types, risk mitigation.",
    "Software Testing": "Unit testing, coverage, early testing, data-driven testing.",
    "Software Maintenance": "Code smells, technical debt, ripple effect, data clumps.",
    "Networking": "TCP/IP, subnetting, routing protocols, OSI layers, firewalls.",
    "AI / ML": "Deep learning, gradient descent, supervised/unsupervised, overfitting, metrics.",
}

TOPIC_BY_NUM: dict[int, str] = {
    1: "C++",
    2: "C++",
    3: "C++",
    4: "C++",
    5: "C++",
    6: "C++",
    7: "C++",
    8: "C++",
    9: "C++",
    10: "C++",
    11: "C++",
    12: "Data Structures",
    13: "Data Structures",
    14: "Data Structures",
    15: "Data Structures",
    16: "Data Structures",
    17: "Data Structures",
    18: "Java / OOP",
    19: "Java / OOP",
    20: "Java / OOP",
    21: "Java / OOP",
    22: "Java / OOP",
    23: "Web Development",
    24: "Web Development",
    25: "Web Development",
    26: "Web Development",
    27: "Web Development",
    28: "Web Development",
    29: "Web Development",
    30: "Web Development",
    31: "Web Development",
    32: "Android",
    33: "Android",
    34: "Android",
    35: "Android",
    36: "Android",
    37: "Database",
    38: "Database",
    39: "Database",
    40: "Database",
    41: "Database",
    42: "Database",
    43: "Operating Systems",
    44: "Operating Systems",
    45: "Operating Systems",
    46: "Operating Systems",
    47: "Operating Systems",
    48: "Operating Systems",
    49: "Software Engineering",
    50: "Software Engineering",
    51: "Software Engineering",
    52: "Software Engineering",
    53: "Software Engineering",
    54: "Software Engineering",
    55: "Requirements Engineering",
    56: "Requirements Engineering",
    57: "Requirements Engineering",
    58: "Requirements Engineering",
    59: "Requirements Engineering",
    60: "Software Architecture",
    61: "Software Architecture",
    62: "Software Architecture",
    63: "Software Architecture",
    64: "Software Architecture",
    65: "Project Management",
    66: "Project Management",
    67: "Project Management",
    68: "Project Management",
    69: "Project Management",
    70: "Software Testing",
    71: "Software Testing",
    72: "Software Testing",
    73: "Software Testing",
    74: "Software Testing",
    75: "Software Maintenance",
    76: "Software Maintenance",
    77: "Software Maintenance",
    78: "Software Maintenance",
    79: "Software Maintenance",
    80: "Networking",
    81: "Networking",
    82: "Networking",
    83: "Networking",
    84: "Networking",
    85: "Networking",
    86: "Networking",
    87: "Networking",
    88: "Networking",
    89: "Networking",
    90: "Networking",
    91: "AI / ML",
    92: "AI / ML",
    93: "AI / ML",
    94: "AI / ML",
    95: "AI / ML",
    96: "AI / ML",
    97: "AI / ML",
    98: "AI / ML",
    99: "AI / ML",
    100: "AI / ML",
}

# Each entry: (text, [(A,text), (B,text), (C,text), (D,text)], answer, topic)
RAW: list[tuple] = [
    ('Which one of the following is a valid identifier name in C++?',
     [("A", '__account'), ("B", 'Total salary'), ("C", 'Tax-rate'), ("D", 'Pay_rate')], "A", "C++"),
    ('Identify the correct C++ control statement used to test more than one condition from the given alternatives.',
     [("A", 'if'), ("B", 'if-else'), ("C", 'switch'), ("D", '?: (conditional operator)')], "C", "C++"),
    ('Which one of the following is the correct syntax for defining a reference variable y to a variable x assuming that x is declared as int (that is, int x;)?',
     [("A", 'int  *y= x;'), ("B", 'int &y=x;'), ("C", 'int &y=&x;'), ("D", 'int  *y=&x;')], "B", "C++"),
    ('One of the following operators is used to dynamically allocate memory in C++.',
     [("A", '?:'), ("B", '::'), ("C", 'new'), ("D", '&')], "C", "C++"),
    ('One of the following is a scope resolution operator in C++>',
     [("A", '::'), ("B", '|'), ("C", 'new'), ("D", '&&')], "A", "C++"),
    ('What is the output of the following C++ program?\n#include <iostream>\nusing namespace std;\n\nint main()\n{\n if(-10)\n{\n cout<<"Welcome";\n}\nelse\n{\n cout<<"Good Bye";\n}\nreturn 0;\n}',
     [("A", 'Good Bye'), ("B", 'Welcome'), ("C", 'WelcomeGood Bye'), ("D", 'Compilation error')], "B", "C++"),
    ('What is the output of the following code?\n#include <iostream>\nusing namespace std;\nvoid compute(int *x, int *y)\n{\n *x=*x+*y;\n *y=*x * *y;\n cout<<*x<<" "<<*y<<endl;\n}\n\nint main(){\n int a=10,b=5;\n compute(&a, &b);\n cout<<a<<" "<<b;\n}',
     [("A", '15   75\n15   75'), ("B", '15  75\n10    5'), ("C", '15  75\n75   15'), ("D", '15  15\n10  10')], "A", "C++"),
    ('What is the output of the following C++ program?\n#include <iostream>\nusing namespace std;\nint main() {\nint a = 10, b = 20;\nint c = (a > b) ? a++ : ++b;\ncout << a << " " << b << " " << c;\nreturn 0;\n}',
     [("A", '11 21 21'), ("B", '1 20 20'), ("C", '10 21 20'), ("D", '10 21 21')], "D", "C++"),
    ('What will be the output of the following code?\nint arr[] = {10, 20, 30, 40, 50};\nint *ptr = arr + 2;\ncout << *ptr << " " << *(ptr + 1);',
     [("A", '20 30'), ("B", '10 20'), ("C", '30 40'), ("D", '40 50')], "C", "C++"),
    ('Which of the following correctly dynamically allocates memory for an array of 10 integers in C++?',
     [("A", 'int arr[10] = new int;'), ("B", 'int *arr = new int[10];'), ("C", 'int *arr = malloc(10 * sizeof(int));'), ("D", 'int arr = new int[10];')], "B", "C++"),
    ('Which mode should be used to open a file for both reading and writing in C++?',
     [("A", 'ios::in'), ("B", 'ios::out'), ("C", 'ios::in | ios::out'), ("D", 'ios::app')], "C", "C++"),
    ('Which of the following is used to implement recursion?',
     [("A", 'Queue'), ("B", 'Stack'), ("C", 'Array'), ("D", 'Linked List')], "B", "Data Structures"),
    ('Which of the following data structures allows deletion at both ends but insertion at only one end?',
     [("A", 'Dequeue'), ("B", 'Queue'), ("C", 'Stack'), ("D", 'Priority Queue')], "A", "Data Structures"),
    ('Which of the following is not a characteristic of arrays?',
     [("A", 'Fixed size'), ("B", 'Random access'), ("C", 'Dynamic resizing'), ("D", 'Contiguous memory allocation')], "C", "Data Structures"),
    ('Which of the following is true about a circular queue?',
     [("A", 'It is a linear data structure'), ("B", 'It overcomes the limitation of linear queue'), ("C", 'It uses a linked list'), ("D", 'It allows insertion at both ends')], "B", "Data Structures"),
    ('Which of the following is not a type of tree traversal?',
     [("A", 'Inorder'), ("B", 'Preorder'), ("C", 'Postorder'), ("D", 'Reverseorder')], "D", "Data Structures"),
    ('Which of the following is not a linear data structure?',
     [("A", 'Array'), ("B", 'Stack'), ("C", 'Queue'), ("D", 'Graph')], "D", "Data Structures"),
    ('A developer argues for using Object-Oriented Programming (OOP) over procedural programming for a national health system that will grow, integrate with other systems, and require frequent updates. Which key advantage of OOP best supports this argument?',
     [("A", 'Faster execution speed'), ("B", 'Reduced memory consumption'), ("C", 'Better modularity and maintainability'), ("D", 'Simpler compilation process')], "C", "Java / OOP"),
    ('In an integrated development environment (IDE), a programmer steps through the execution of a program line by line while inspecting variable values to understand why a logical error occurs during runtime. Which IDE feature is the programmer primarily using?',
     [("A", 'Code editor'), ("B", 'Compiler'), ("C", 'Build tool'), ("D", 'Debugger')], "D", "Java / OOP"),
    ('A software architect emphasizes designing classes that represent concepts in the problem domain rather than focusing on implementation details. This allows developers to reason about the system at a higher level of understanding. Which object-oriented concept is being emphasized?',
     [("A", 'Encapsulation'), ("B", 'Abstraction'), ("C", 'Inheritance'), ("D", 'Polymorphism')], "B", "Java / OOP"),
    ('Consider a banking application where the account balance must not be modified directly by external classes to prevent unauthorized transactions. The developer hides the balance variable and allows access only through controlled methods. Which object-oriented concept is primarily used to achieve this protection?',
     [("A", 'Encapsulation'), ("B", 'Polymorphism'), ("C", 'Inheritance'), ("D", 'Abstraction')], "A", "Java / OOP"),
    ('Examine the following class definition:\nclass Account {\n    private double balance;\n}\nFrom a software engineering perspective, why is declaring balance as private considered good design practice?',
     [("A", 'It reduces memory usage'), ("B", 'It improves execution speed'), ("C", 'It simplifies inheritance'), ("D", 'It prevents unauthorized direct access to sensitive data')], "D", "Java / OOP"),
    ('Which programming language is mainly used for client-side scripting to add interactivity to web pages?',
     [("A", 'PHP'), ("B", 'Java'), ("C", 'Python'), ("D", 'JavaScript')], "D", "Web Development"),
    ('Which of the following best describes the role of a web server?',
     [("A", 'Executes client-side scripts only'), ("B", 'Stores and processes client requests and delivers web resources'), ("C", 'Designs the user interface'), ("D", 'Manages user authentication only')], "B", "Web Development"),
    ('Which combination correctly represents a typical web technology stack?',
     [("A", 'HTML, CSS, JavaScript'), ("B", 'Java, C++, Assembly'), ("C", 'SQL, XML, JSON'), ("D", 'Photoshop, Illustrator, Figma')], "A", "Web Development"),
    ('Which shorthand property correctly sets margin-top and margin-bottom to 20px and margin-left and margin-right to 10px?',
     [("A", 'margin: 10px 20px;'), ("B", 'margin: 20px 10px;'), ("C", 'margin: 20px 10px 20px 10px;'), ("D", 'margin: 10px 20px 10px 20px;')], "B", "Web Development"),
    ("Which CSS rule ensures that padding and border are included in an element's total width and height?",
     [("A", 'box-sizing: content-box;'), ("B", 'box-model: border-box;'), ("C", 'box-sizing: border-box;'), ("D", 'display: border-box;')], "C", "Web Development"),
    ('Consider this CSS code. Relative to what is the element positioned?\ndiv {\nposition: absolute;\ntop: 50px; }',
     [("A", 'The browser window always'), ("B", 'The nearest positioned ancestor'), ("C", 'The parent element only'), ("D", 'The document body only')], "B", "Web Development"),
    ('When implementing Progressive Web App (PWA) features, which combination provides the BEST offline experience?',
     [("A", 'Service Worker + Cache API'), ("B", 'Service Worker + Web App Manifest'), ("C", 'Local Storage + Cache API'), ("D", 'IndexedDB + Cookies')], "A", "Web Development"),
    ('Given the following CSS:\n.box {\nwidth: 300px;\npadding: 20px;\nborder: 10px solid;\nbox-sizing: border-box;\n}\nWhat is the actual rendered width of .box?',
     [("A", '300px'), ("B", '340px'), ("C", '360px'), ("D", '400px')], "A", "Web Development"),
    ('What happens when a user requests a page on a dynamic website?',
     [("A", 'The server sends a pre-built HTML file'), ("B", 'The server generates the HTML on the fly using server-side scripts'), ("C", 'The browser automatically creates the HTML'), ("D", 'The page cannot be displayed')], "B", "Web Development"),
    ('What is the primary purpose of the AndroidManifest.xml file?',
     [("A", 'To store the visual layout of the application screens'), ("B", 'To contain the Java/Kotlin source code for business logic'), ("C", 'To manage the local SQLite database versioning'), ("D", 'To define the essential information about the app for the Android system')], "D", "Android"),
    ('What does the "R" file in Android development represent?',
     [("A", 'A file containing the Raw assets like MP3s'), ("B", 'A dynamically generated class containing resource IDs'), ("C", 'The Runtime configuration for the Dalvik Virtual Machine'), ("D", 'The Repository link for Gradle dependencies')], "B", "Android"),
    ('In mobile computing, what is the role of a "Broadcast Receiver"?',
     [("A", 'To respond to system-wide announcement notifications'), ("B", 'To navigate between different app screens'), ("C", 'To play audio and video streams from a URL'), ("D", 'To manage the synchronization of data with a remote server')], "A", "Android"),
    ('Which of the following best describes "Fragments" in Android?',
     [("A", 'They are small portions of the SQLite database'), ("B", 'They are modular sections of an activity with their own lifecycle'), ("C", 'They are external libraries used for network requests'), ("D", 'They are error messages shown when an app crashes')], "B", "Android"),
    ('A developer wants to ensure that a long-running network task does not block the UI thread. What is the correct implementation strategy?',
     [("A", 'Run the task inside the onCreate() method directly'), ("B", 'Increase the CPU priority of the main thread'), ("C", 'Use a background thread or Coroutines/AsyncTask'), ("D", 'Call Thread.sleep() before the network request')], "C", "Android"),
    ('Which of the following SQL command is used to add new records in database?',
     [("A", 'Add'), ("B", 'Update'), ("C", 'Insert'), ("D", 'Create')], "C", "Database"),
    ('What is composite attribute?',
     [("A", 'An attribute that can take more than one value for each entity instance'), ("B", 'An attribute that can be split into components'), ("C", 'An attribute that can be derived based on other attributes'), ("D", 'An attribute that takes values from same domain')], "B", "Database"),
    ('The cardinality of a relation in relational database refers to',
     [("A", 'The number of instances'), ("B", 'The domain of attribute values'), ("C", 'The number of columns'), ("D", 'The order of columns')], "A", "Database"),
    ('In relational data model, a relation schema is made of',
     [("A", 'Relation name and data types'), ("B", 'Relation name and list of attributes'), ("C", 'List of attributes and domain values'), ("D", 'Entity set and list of attributes')], "B", "Database"),
    ('Which of the following is SQL Data Manipulation (DML) command?',
     [("A", 'Add'), ("B", 'Drop'), ("C", 'Create'), ("D", 'Update')], "D", "Database"),
    ('The primary purpose of referential integrity constraint is -------------------',
     [("A", 'To uniquely identify individual record from the two relations'), ("B", 'To maintain the consistency among tuples in the two relations'), ("C", 'Ensuring within each tuple, the value of each attribute is from same domain'), ("D", 'To prevent data redundancy and avoid insertion anomalies in a database')], "B", "Database"),
    ('In which one of the following page replacement algorithms it is possible for the page fault rate to increase even when the number of allocated frames increases?',
     [("A", 'LRU (Least Recently Used)'), ("B", 'OPT (Optimal Page Replacement)'), ("C", 'MRU (Most Recently Used)'), ("D", 'FIFO (First In First Out)')], "D", "Operating Systems"),
    ('A thread differs from a process because a thread:',
     [("A", 'Has its own address space'), ("B", 'Is heavyweight'), ("C", 'Shares address space with other threads'), ("D", 'Cannot run independently')], "C", "Operating Systems"),
    ('Which of the following increases overhead in an OS?',
     [("A", 'Paging'), ("B", 'Context switching'), ("C", 'Multithreading'), ("D", 'Virtual memory')], "B", "Operating Systems"),
    ('A process moves from Running to Waiting state when:',
     [("A", 'Time quantum expires'), ("B", 'I/O operation is requested'), ("C", 'Process terminates'), ("D", 'Scheduler selects another process')], "B", "Operating Systems"),
    ('Zombie process is a process that:',
     [("A", 'Is running'), ("B", 'Is waiting for I/O'), ("C", 'Has terminated but PCB exists'), ("D", 'Is deadlocked')], "C", "Operating Systems"),
    ('The primary goal of operating system security is to ensure:',
     [("A", 'High performance'), ("B", 'Confidentiality, Integrity, and Availability'), ("C", 'Faster execution'), ("D", 'Better user interface')], "B", "Operating Systems"),
    ('What is the primary emphasis of the spiral model?',
     [("A", 'Phased software development'), ("B", 'Throwaway prototyping'), ("C", 'Risk-driven development'), ("D", 'Incremental development')], "C", "Software Engineering"),
    ('What best describes evolutionary prototyping?',
     [("A", 'Phased software development'), ("B", 'Throwaway prototyping'), ("C", 'Risk-driven development'), ("D", 'Incremental development')], "D", "Software Engineering"),
    ('What is a software life-cycle?',
     [("A", 'The operational lifespan of software'), ("B", 'A cyclic approach to software development'), ("C", 'A phased approach to software development'), ("D", 'The lifespan of cyclically developed software')], "C", "Software Engineering"),
    ('What activities are performed during incremental software construction?',
     [("A", 'Detailed design and coding of classes in a system subset'), ("B", 'Detailed design, coding, and unit testing of classes in a system subset'), ("C", 'Coding and unit testing of classes in a system subset'), ("D", 'Unit and integration testing of classes in a system subset')], "B", "Software Engineering"),
    ('If you need to develop software within a strict deadline with unlimited budget, which development model would you choose?',
     [("A", 'Waterfall'), ("B", 'Spiral'), ("C", 'RAD (Rapid Application Development)'), ("D", 'Incremental')], "C", "Software Engineering"),
    ('Which type of CASE tools support early process activities like requirements and design?',
     [("A", 'Lower-CASE'), ("B", 'Upper-CASE'), ("C", 'System-CASE'), ("D", 'Test-CASE')], "B", "Software Engineering"),
    ('Requirements Engineering mainly acts as a bridge between_______.',
     [("A", 'Stakeholders and developers'), ("B", 'Hardware and software'), ("C", 'Developers and testers'), ("D", 'Users and databases')], "A", "Requirements Engineering"),
    ('Which phase of SDLC is most directly supported by Requirements Engineering?',
     [("A", 'Maintenance'), ("B", 'Deployment'), ("C", 'Analysis'), ("D", 'Implementation')], "C", "Requirements Engineering"),
    ('Poor requirements engineering most commonly leads to_______?',
     [("A", 'Faster development'), ("B", 'Cost overruns and project failure'), ("C", 'Reduced documentation'), ("D", 'Improved performance')], "B", "Requirements Engineering"),
    ('A large organization plans to implement a new enterprise resource planning system. The system definition document describes the overall system context, boundaries, and how it aligns with organizational goals. What is the primary purpose of preparing such a document before detailed design begins?',
     [("A", 'Define overall system scope and context'), ("B", 'Describe algorithms'), ("C", 'Replace the SRS'), ("D", 'Specify user interfaces')], "A", "Requirements Engineering"),
    ('Requirements Engineering contributes to project success mainly by:',
     [("A", 'Reducing hardware costs'), ("B", 'Clarifying expectations early'), ("C", 'Increasing programming speed'), ("D", 'Eliminating documentation')], "B", "Requirements Engineering"),
    ('Which artifact best represents architectural decisions?',
     [("A", 'Source code'), ("B", 'UML class diagram'), ("C", 'Architecture documentation'), ("D", 'Test cases')], "C", "Software Architecture"),
    ('Which factor has the greatest long-term impact on system evolution?',
     [("A", 'Variable naming'), ("B", 'UI color'), ("C", 'Architectural structure'), ("D", 'Code formatting')], "C", "Software Architecture"),
    ('Architecture decisions are difficult to change because they:',
     [("A", 'Are undocumented'), ("B", 'Affect multiple quality attributes'), ("C", 'Only impact performance'), ("D", 'Are optional')], "B", "Software Architecture"),
    ('Which stakeholder is MOST concerned with scalability?',
     [("A", 'End user'), ("B", 'Tester'), ("C", 'UI designer'), ("D", 'Architect')], "D", "Software Architecture"),
    ('Architecture differs from design mainly by its:',
     [("A", 'Level of abstraction'), ("B", 'Programming language'), ("C", 'Number of classes'), ("D", 'Testing approach')], "A", "Software Architecture"),
    ("The PM decides to use PERT for the new feature's estimation. If the Optimistic time is 4 days, Most likely is 7 days, and Pessimistic is 16 days, what is the expected duration?",
     [("A", '7 days'), ("B", '8 days'), ("C", '9 days'), ("D", '10 days')], "B", "Project Management"),
    ('Which management activity is most critical when the team lead suddenly resigns during the "Execution" phase?',
     [("A", 'Configuration Management'), ("B", 'Risk Mitigation'), ("C", 'Requirement Validation'), ("D", 'Perfective Maintenance')], "B", "Project Management"),
    ('The team is using a "Scrum" framework. During the Sprint Review, the customer realizes the UI is not intuitive. Which SPM document was likely poorly defined at the start?',
     [("A", 'Software Requirement Specification (SRS)'), ("B", 'Work Breakdown Structure (WBS)'), ("C", 'Project Charter'), ("D", 'Risk Register')], "A", "Project Management"),
    ('Management wants to add a new "Real-time Analytics" dashboard to the existing system. This falls under:',
     [("A", 'Corrective Maintenance'), ("B", 'Adaptive Maintenance'), ("C", 'Perfective Maintenance'), ("D", 'Preventive Maintenance')], "C", "Project Management"),
    ('Which model provides a framework for "Continuous Process Improvement" in software organizations?',
     [("A", 'Waterfall'), ("B", 'CMMI (Capability Maturity Model Integration)'), ("C", 'V-Model'), ("D", 'RAD Model')], "B", "Project Management"),
    ('Why is software testing crucial in the Software Development Life Cycle (SDLC)?',
     [("A", 'It ensures that the software functions correctly and meets user expectations'), ("B", 'It eliminates all defects from the software'), ("C", 'It speeds up the development process'), ("D", 'It guarantees the software will never fail')], "A", "Software Testing"),
    ('A finance company needs to verify that its fraud detection algorithm correctly flags suspicious transactions. The system must detect fraudulent activity while avoiding false positives. What testing approach is most suitable?',
     [("A", 'Regression Testing'), ("B", 'Exploratory Testing'), ("C", 'Data-Driven Testing'), ("D", 'Smoke Testing')], "C", "Software Testing"),
    ('In the context of test case design, what is a key measurement used to assess test coverage?',
     [("A", 'Number of test cases executed'), ("B", 'Percentage of requirements tested'), ("C", 'Amount of time taken for testing'), ("D", 'Number of defects reported')], "B", "Software Testing"),
    ('Which principle of software testing states that testing should start as early as possible in the SDLC?',
     [("A", 'Exhaustive testing is impossible'), ("B", 'Defect clustering'), ("C", 'Early testing'), ("D", 'Pesticide paradox')], "C", "Software Testing"),
    ('In which scenario would unit testing be most beneficial?',
     [("A", 'Testing a complex integration between multiple services'), ("B", 'Ensuring that an individual function in a program behaves correctly'), ("C", 'Validating security vulnerabilities in a web application'), ("D", 'Measuring system performance under peak load')], "B", "Software Testing"),
    ('In a legacy system, you find that changing a single requirement requires modifying 15 different classes. How would you evaluate this architectural state?',
     [("A", 'The system is exhibiting "Shotgun Surgery," indicating poor encapsulation'), ("B", 'The system is exhibiting "Divergent Change," indicating a lack of cohesion'), ("C", 'The system is following the Open-Closed Principle correctly'), ("D", 'The system is optimized for high-performance execution')], "A", "Software Maintenance"),
    ('When evaluating the impact of "Feature Envy," what is the primary structural concern?',
     [("A", 'The method is excessively long and difficult to unit test'), ("B", 'The method is more interested in the data of a class other than the one it is in'), ("C", 'The method uses too many local variables, increasing memory consumption'), ("D", 'The method is duplicated across multiple subclasses in a hierarchy')], "B", "Software Maintenance"),
    ('You are evaluating a system where "Technical Debt" is high. Which metric would best serve as an indicator of structural decay over time?',
     [("A", 'The total number of lines of code in the master branch'), ("B", 'The ratio of comment lines to executable code lines'), ("C", 'The increase in Cyclomatic Complexity relative to the number of new features added'), ("D", 'The number of developers assigned to the maintenance phase')], "C", "Software Maintenance"),
    ('A system has a high frequency of "Ripple Effect" defects. What is the most likely evaluation of its design?',
     [("A", 'High module cohesion and low coupling'), ("B", 'High degree of global variable usage and tight coupling'), ("C", 'Use of strict interfaces and dependency injection'), ("D", 'Excessive use of inheritance rather than composition')], "B", "Software Maintenance"),
    ('Evaluate the "Data Clump" smell. What is the most effective way to judge if a group of variables constitutes a clump?',
     [("A", 'They are always passed together as parameters across different methods'), ("B", 'They are all defined as static constants in a configuration file'), ("C", 'They are all of the same primitive data type'), ("D", 'They are used only within a single private method')], "A", "Software Maintenance"),
    ('In the TCP/IP model, which layer corresponds to the Network Layer in the OSI model?',
     [("A", 'Application Layer'), ("B", 'Transport Layer'), ("C", 'Internet Layer'), ("D", 'Network Access Layer')], "C", "Networking"),
    ('What is the default subnet mask for a Class B IP address?',
     [("A", '255.0.0.0'), ("B", '255.255.0.0'), ("C", '255.255.255.0'), ("D", '255.255.255.255')], "B", "Networking"),
    ('Which protocol is used for resolving IP addresses to MAC addresses?',
     [("A", 'DNS'), ("B", 'DHCP'), ("C", 'ARP'), ("D", 'ICMP')], "C", "Networking"),
    ('What is the primary purpose of the DHCP protocol?',
     [("A", 'To resolve domain names to IP addresses'), ("B", 'To route packets between networks'), ("C", 'To detect errors in data transmission'), ("D", 'To assign IP addresses dynamically to devices')], "D", "Networking"),
    ('Which protocol is used for sending email from a client to a server?',
     [("A", 'POP3'), ("B", 'IMAP'), ("C", 'SMTP'), ("D", 'FTP')], "C", "Networking"),
    ('Which routing protocol uses the Dijkstra algorithm to find the shortest path?',
     [("A", 'RIP'), ("B", 'OSPF'), ("C", 'BGP'), ("D", 'EIGRP')], "B", "Networking"),
    ('What is the purpose of a default gateway in a network?',
     [("A", 'To connect devices within the same subnet'), ("B", 'To route traffic to devices outside the local network'), ("C", 'To assign IP addresses to devices'), ("D", 'To filter incoming and outgoing traffic')], "B", "Networking"),
    ('What is the purpose of a firewall in a network?',
     [("A", 'To assign IP addresses to devices'), ("B", 'To resolve domain names to IP addresses'), ("C", 'To filter incoming and outgoing traffic based on security rules'), ("D", 'To detect physical layer errors')], "C", "Networking"),
    ('Which device operates at the Data Link Layer of the OSI model?',
     [("A", 'Router'), ("B", 'Switch'), ("C", 'Hub'), ("D", 'Repeater')], "B", "Networking"),
    ('What is the main disadvantage of a bus topology?',
     [("A", 'High cost of implementation'), ("B", 'Difficulty in troubleshooting'), ("C", 'Single point of failure'), ("D", 'Limited scalability')], "C", "Networking"),
    ('What is the maximum speed of a standard Ethernet network?',
     [("A", '10 Mbps'), ("B", '100 Mbps'), ("C", '1 Gbps'), ("D", '10 Gbps')], "A", "Networking"),
    ('What does the term "deep" specifically refer to in the context of deep learning?',
     [("A", 'The complexity of the mathematical functions used'), ("B", 'The amount of training data required for accuracy'), ("C", 'The number of functions or layers in the network'), ("D", 'The width of the hidden layers')], "C", "AI / ML"),
    ('Which of the following is NOT an application of AI?',
     [("A", 'Weather prediction using fixed formulas only'), ("B", 'Medical diagnosis'), ("C", 'Autonomous vehicles'), ("D", 'Face recognition')], "A", "AI / ML"),
    ('In gradient descent, what is the role of the momentum parameter?',
     [("A", 'It acts as a static step size that never changes'), ("B", 'It ensures the weights are always initialized to zero'), ("C", 'It is used to randomly drop units during the training process'), ("D", 'It acts like a velocity of the step size to increase or decrease speed based on direction')], "D", "AI / ML"),
    ('Machine learning mainly focuses on:',
     [("A", 'Writing rules manually'), ("B", 'Learning patterns from data'), ("C", 'Hardware design'), ("D", 'Internet communication')], "B", "AI / ML"),
    ('What is the main purpose of using Dropout during the training of a neural network?',
     [("A", 'To increase the learning rate of the output layer'), ("B", 'To scale the prediction during training'), ("C", 'To replace missing data points in the training set'), ("D", 'To prevent overfitting by randomly setting some unit outputs to zero')], "D", "AI / ML"),
    ('Which type of learning uses labeled data?',
     [("A", 'Unsupervised learning'), ("B", 'Reinforcement learning'), ("C", 'Supervised learning'), ("D", 'Deep learning')], "C", "AI / ML"),
    ('Which of the following is an example of supervised learning?',
     [("A", 'Clustering customers by behaviour'), ("B", 'Spam email classification'), ("C", 'Discovering hidden patterns'), ("D", 'Dimensionality reduction')], "B", "AI / ML"),
    ('Unsupervised learning is mainly used for:',
     [("A", 'Prediction with known outputs'), ("B", 'Classification with labels'), ("C", 'Finding patterns in unlabeled data'), ("D", 'Decision making with rewards')], "C", "AI / ML"),
    ('Overfitting occurs when a model:',
     [("A", 'Performs well on new data'), ("B", 'Is too simple'), ("C", 'Learns noise instead of patterns'), ("D", 'Has too little data')], "C", "AI / ML"),
    ('Which metric is commonly used to evaluate classification models?',
     [("A", 'Mean squared error'), ("B", 'Accuracy'), ("C", 'Variance'), ("D", 'Correlation')], "B", "AI / ML"),
]

assert len(RAW) == 100, f"Expected 100 questions, got {len(RAW)}"
