"""ASTU 3rd Round Model Exit Exam 2026 — Software Engineering (100 MCQs)."""

from __future__ import annotations

FOCUS_GUIDE: dict[str, str] = {
    "Fundamentals of Programming": "C++ arrays, pointers, references, I/O, memory (stack/heap), file modes.",
    "Data Structures": "Stacks, queues, deques, arrays, circular queues, tree traversals.",
    "Java / OOP": "Abstract classes, interfaces, inheritance, constructors, event-driven programming.",
    "Web Development": "HTML/CSS/JS stack, HTTP, Django, SOA, microservices, session management.",
    "Android": "Fragments, Room, RecyclerView, mobile security, ethical framework choice.",
    "Database": "ACID, ER diagrams, DBMS, concurrency, weak entities, OODBMS.",
    "Operating Systems": "fork(), PCB, scheduling, Banker's algorithm, file allocation, synchronization.",
    "Software Engineering": "SDLC, modularity, requirements engineering, scope creep, black-box testing.",
    "Software Architecture": "Singleton, Mediator, cohesion/coupling, architecture documentation, NFRs.",
    "Project Management": "COCOMO, Scrum/SRS, risk, lag, regression vs corrective maintenance.",
    "Software Testing": "Functional testing, ISO 25010 usability, Law of Demeter, ACT, exit criteria.",
    "Software Maintenance": "Perfective maintenance, reverse engineering, CFG/call graphs.",
    "Networking": "Private IP, DHCP, OSI layers, subnet masks, TCP/IP, ACL, bus topology.",
    "Security": "CIA triad (Confidentiality), DoS attacks, malware (Trojan).",
    "AI / ML": "Bayesian inference, utility agents, BFS, A*, Turing Test, knowledge representation.",
}


def TOPIC_BY_NUM(n: int) -> str:
    """Map question number 1–100 to topic per PDF section outline."""
    if 1 <= n <= 11:
        return "Fundamentals of Programming"
    if 12 <= n <= 17:
        return "Data Structures"
    if 18 <= n <= 22:
        return "Java / OOP"
    if 23 <= n <= 31:
        return "Web Development"
    if 32 <= n <= 36:
        return "Android"
    if 37 <= n <= 42:
        return "Database"
    if 43 <= n <= 48:
        return "Operating Systems"
    if 49 <= n <= 54:
        return "Software Engineering"
    if 55 <= n <= 59:
        return "Software Engineering"
    if 60 <= n <= 64:
        return "Software Architecture"
    if 65 <= n <= 69:
        return "Project Management"
    if 70 <= n <= 74:
        return "Software Testing"
    if 75 <= n <= 79:
        return "Software Maintenance"
    if 80 <= n <= 84:
        return "Networking"
    if n in (85, 86):
        return "Security"
    if 87 <= n <= 90:
        return "Networking"
    if n == 91:
        return "Security"
    if 92 <= n <= 100:
        return "AI / ML"
    raise ValueError(f"Invalid question number: {n}")


# Each entry: (text, [(A,text), (B,text), (C,text), (D,text)], answer, topic)
# PDF numbering fixes: Q8 = pointer-output (mislabeled E after Q7); duplicate PDF Q85
# split into Q85 (Confidentiality) and Q86 (DoS); Q87–100 = PDF 86–98, 100 (PDF 99 omitted).
RAW: list[tuple] = [

    ('Which of the following correctly declares an array of 10 integers in C++?',
     [("A", 'int arr[10];'),
      ("B", 'int arr = new int[10];'),
      ("C", 'array<int> arr;'),
      ("D", 'int arr(10);')], "A", "Fundamentals of Programming"),
    ('What does the expression *(ptr + i) represent in C++?',
     [("A", 'Value at index i'),
      ("B", 'Address of array'),
      ("C", 'Function call'),
      ("D", 'Variable declaration')], "A", "Fundamentals of Programming"),
    ('Which conditional statement is used to execute code only if a condition is true?',
     [("A", 'switch'),
      ("B", 'if'),
      ("C", 'for'),
      ("D", 'while')], "B", "Fundamentals of Programming"),
    ('Which of the following is a valid variable name in C++?',
     [("A", '2value'),
      ("B", 'value_2'),
      ("C", 'float'),
      ("D", '#var')], "B", "Fundamentals of Programming"),
    ('What is the default value of local variables in C++?',
     [("A", 'Zero'),
      ("B", 'Null'),
      ("C", 'Garbage value'),
      ("D", 'False')], "C", "Fundamentals of Programming"),
    ('Which header file is needed for input/output in C++?',
     [("A", '<stdio.h>'),
      ("B", '<iostream>'),
      ("C", '<fstream>'),
      ("D", '<stdlib.h>')], "B", "Fundamentals of Programming"),
    ('Which one of the following is the correct syntax for defining a reference variable y to a variable x assuming that x is declared as int (that is, int x;)?',
     [("A", 'int *y= x;'),
      ("B", 'int &y=x;'),
      ("C", 'int &y=&x;'),
      ("D", 'int *y=&x;')], "B", "Fundamentals of Programming"),
    ('What will be the output of the following code?\nint arr[] = {10, 20, 30, 40, 50};\nint *ptr = arr + 2;\ncout << *ptr << " " << *(ptr + 1);',
     [("A", '20 30'),
      ("B", '10 20'),
      ("C", '30 40'),
      ("D", '40 50')], "C", "Fundamentals of Programming"),
    ('Which of the following correctly dynamically allocates memory for an array of 10 integers in C++?',
     [("A", 'int arr[10] = new int;'),
      ("B", 'int *arr = new int[10];'),
      ("C", 'int *arr = malloc(10 * sizeof(int));'),
      ("D", 'int arr = new int[10];')], "B", "Fundamentals of Programming"),
    ('What is the primary reason why the following code exhibits undefined behavior?\nint* createArray() {\n    int arr[5] = {1, 2, 3, 4, 5};\n    return arr;\n}',
     [("A", 'The array is allocated on the stack and will be destroyed when the function returns'),
      ("B", 'Arrays cannot be returned from functions in C++'),
      ("C", 'The array size is not specified in the return type'),
      ("D", 'Integer arrays require dynamic allocation to be returned')], "A", "Fundamentals of Programming"),
    ('What is the fundamental difference between stack and heap memory allocation in C++?',
     [("A", 'Stack allocation is slower but more flexible; heap allocation is faster but limited in size'),
      ("B", 'Stack allocation is automatic with fixed lifetime (scope-based); heap allocation is manual with dynamic lifetime'),
      ("C", 'Stack is used for global variables; heap is used for local variables'),
      ("D", 'Stack memory can only store primitive types; heap can store any data type')], "B", "Fundamentals of Programming"),
    ('Which of the following is used to implement recursion?',
     [("A", 'Queue'),
      ("B", 'Stack'),
      ("C", 'Array'),
      ("D", 'Linked List')], "B", "Data Structures"),
    ('Which of the following data structures allows deletion at both ends but insertion at only one end?',
     [("A", 'Queue'),
      ("B", 'Dequeue'),
      ("C", 'Stack'),
      ("D", 'Priority Queue')], "B", "Data Structures"),
    ('Which of the following is not a characteristic of arrays?',
     [("A", 'Fixed size'),
      ("B", 'Random access'),
      ("C", 'Dynamic resizing'),
      ("D", 'Contiguous memory allocation')], "C", "Data Structures"),
    ('Which of the following is true about a circular queue?',
     [("A", 'It is a linear data structure'),
      ("B", 'It uses a linked list'),
      ("C", 'It overcomes the limitation of linear queue'),
      ("D", 'It allows insertion at both ends')], "C", "Data Structures"),
    ('Which of the following is not a type of tree traversal?',
     [("A", 'Inorder'),
      ("B", 'Preorder'),
      ("C", 'Postorder'),
      ("D", 'Reverseorder')], "D", "Data Structures"),
    ('What is a key characteristic of a queue data structure?',
     [("A", 'Last-In-First-Out (LIFO) methodology'),
      ("B", 'First-In-Last-Out (FILO) methodology'),
      ("C", 'First-In-First-Out (FIFO) methodology'),
      ("D", 'Random access of elements.')], "C", "Data Structures"),
    ('What is the primary difference between an Abstract Class and an Interface?',
     [("A", 'Abstract classes can have constructors, while interfaces cannot.'),
      ("B", 'Interfaces can have private methods, while abstract classes cannot.'),
      ("C", 'A class can extend multiple abstract classes but only one interface.'),
      ("D", 'Abstract classes only contain static variables.')], "A", "Java / OOP"),
    ('If class `Manager` inherits from class `Employee`, and `Employee` inherits from `Person`, this is an example of:',
     [("A", 'Single Inheritance'),
      ("B", 'Hierarchical Inheritance'),
      ("C", 'Multilevel Inheritance'),
      ("D", 'Multiple Inheritance')], "C", "Java / OOP"),
    ('What is the result of attempting to instantiate an abstract class?',
     [("A", 'The program runs and creates an empty object.'),
      ("B", 'The compiler throws an error because the class is incomplete.'),
      ("C", 'The JVM creates a default implementation at runtime.'),
      ("D", 'The object is created but all its methods are null.')], "B", "Java / OOP"),
    ('When a subclass constructor does not explicitly call a superclass constructor, what does the Java compiler do?',
     [("A", 'It skips the superclass initialization.'),
      ("B", 'It throws a compile-time error.'),
      ("C", 'It inserts an implicit call to `super()`.'),
      ("D", 'It initializes only the static members of the superclass.')], "C", "Java / OOP"),
    ('A graphical user interface application responds to button clicks, mouse movements, and keyboard input rather than executing instructions sequentially. Which programming model does this describe?',
     [("A", 'Procedural programming'),
      ("B", 'Functional programming'),
      ("C", 'Event-driven programming'),
      ("D", 'Logic programming')], "C", "Java / OOP"),
    ('Which programming language is mainly used for client-side scripting to add interactivity to web pages?',
     [("A", 'PHP'),
      ("B", 'Java'),
      ("C", 'JavaScript'),
      ("D", 'Python')], "C", "Web Development"),
    ('Which of the following best describes the role of a web server?',
     [("A", 'Manages user authentication only'),
      ("B", 'Executes client-side scripts only'),
      ("C", 'Stores and processes client requests and delivers web resources'),
      ("D", 'Designs the user interface')], "C", "Web Development"),
    ('Which combination correctly represents a typical web technology stack?',
     [("A", 'HTML, CSS, JavaScript'),
      ("B", 'Java, C++, Assembly'),
      ("C", 'SQL, XML, JSON'),
      ("D", 'Photoshop, Illustrator, Figma')], "A", "Web Development"),
    ('Which of the following is an example of a server-side web framework?',
     [("A", 'Bootstrap'),
      ("B", 'React'),
      ("C", 'Django'),
      ("D", 'jQuery')], "C", "Web Development"),
    ('You need to choose between Monolithic and Microservices architecture. Which factor would MOST strongly favor Microservices?',
     [("A", 'Small development team (2–3 developers)'),
      ("B", 'Application with tightly coupled modules'),
      ("C", 'Requirement for independent scaling of different components'),
      ("D", 'Simple CRUD application with minimal business logic')], "C", "Web Development"),
    ('What is middleware in server-side frameworks?',
     [("A", 'Database software'),
      ("B", 'Code that handles requests between client and server logic'),
      ("C", 'Frontend UI code'),
      ("D", 'Network hardware')], "B", "Web Development"),
    ('Which protocol is primarily used for communication between web clients and servers?',
     [("A", 'FTP'),
      ("B", 'SMTP'),
      ("C", 'HTTP'),
      ("D", 'SNMP')], "C", "Web Development"),
    ('What is session management mainly used for?',
     [("A", 'Encrypting data'),
      ("B", 'Maintaining user state across requests'),
      ("C", 'Styling web pages'),
      ("D", 'Handling DNS queries')], "B", "Web Development"),
    ('What is Service-Oriented Architecture (SOA)?',
     [("A", 'A programming language'),
      ("B", 'A hardware design model'),
      ("C", 'An architectural style based on reusable services'),
      ("D", 'A database management technique')], "C", "Web Development"),
    ('When selecting a mobile development framework (e.g., Flutter vs Native), why is "Long-term Sustainability" an ethical consideration?',
     [("A", 'To ensure the developer gets paid for more hours'),
      ("B", "To protect the client's investment and ensure the app remains maintainable and secure in the future"),
      ("C", 'Because newer frameworks always have better colors'),
      ("D", 'To prevent the app from being cloned by competitors')], "B", "Android"),
    ("What is the most secure way to evaluate and store a user's password locally on a mobile device?",
     [("A", 'Store it as a plain text String in Shared Preferences'),
      ("B", 'Store a salted hash of the password'),
      ("C", 'Encrypt it using Base64 and save to a public folder'),
      ("D", 'Avoid local storage; only verify via a secure server-side API')], "D", "Android"),
    ('Which of the following best describes "Fragments" in Android?',
     [("A", 'They are small portions of the SQLite database'),
      ("B", 'They are modular sections of an activity with their own lifecycle'),
      ("C", 'They are external libraries used for network requests'),
      ("D", 'They are error messages shown when an app crash')], "B", "Android"),
    ('When using the Room Persistence Library, which annotation is used to define a class as a database table?',
     [("A", '@Database'),
      ("B", '@Table'),
      ("C", '@Entity'),
      ("D", '@ColumnInfo')], "C", "Android"),
    ('A developer needs to display a list of 1,000 items efficiently without consuming excessive memory. Which component is the best choice?',
     [("A", 'ScrollView'),
      ("B", 'ListView'),
      ("C", 'RecyclerView'),
      ("D", 'ViewPager')], "C", "Android"),
    ('Concurrency control prevents the Incorrect Summary Problem when:',
     [("A", 'One transaction calculates an aggregate while another updates data'),
      ("B", 'A system error occurs'),
      ("C", 'An exception is detected by one transaction'),
      ("D", 'A disk failure happens')], "A", "Database"),
    ('Which ACID property ensures that a transaction transforms the database from one valid state to another valid state?',
     [("A", 'Atomicity'),
      ("B", 'Isolation'),
      ("C", 'Durability'),
      ("D", 'Consistency')], "D", "Database"),
    ('Why is a weak entity included in an ER diagram?',
     [("A", 'It depends on another entity for identification'),
      ("B", 'To automatically optimize queries'),
      ("C", 'To reduce storage space'),
      ("D", 'It does not need a primary key')], "A", "Database"),
    ('How does controlling data redundancy improve reliability?',
     [("A", 'By increasing storage requirements'),
      ("B", 'By speeding up queries automatically'),
      ("C", 'By automatically indexing tables'),
      ("D", 'By preventing inconsistent or duplicate data')], "D", "Database"),
    ('Which of the following best describes a Database Management System (DBMS)?',
     [("A", 'A collection of logically related data'),
      ("B", 'A software that manages data and provides controlled access to it'),
      ("C", 'A programming language for database design'),
      ("D", 'A hardware device for storing data')], "B", "Database"),
    ('Which feature distinguishes object-oriented databases from relational ones?',
     [("A", 'Only stores tabular data'),
      ("B", 'Cannot be queried'),
      ("C", 'Uses hierarchical links only'),
      ("D", 'Supports complex types, encapsulation, and inheritance')], "D", "Database"),
    ('Which system call creates a new process in UNIX/Linux?',
     [("A", 'exec()'),
      ("B", 'wait()'),
      ("C", 'exit()'),
      ("D", 'fork()')], "D", "Operating Systems"),
    ('The Producer–Consumer problem is an example of:',
     [("A", 'Deadlock'),
      ("B", 'Synchronization'),
      ("C", 'Starvation'),
      ("D", 'Scheduling')], "B", "Operating Systems"),
    ('A process control block (PCB) does NOT contain:',
     [("A", 'Process state'),
      ("B", 'Program counter'),
      ("C", 'CPU registers'),
      ("D", 'Program source code')], "D", "Operating Systems"),
    ('Which file allocation method supports efficient direct access?',
     [("A", 'Indexed allocation'),
      ("B", 'Linked allocation'),
      ("C", 'Sequential allocation'),
      ("D", 'Contiguous allocation')], "A", "Operating Systems"),
    ("The Banker's algorithm is primarily used for:",
     [("A", 'Deadlock prevention'),
      ("B", 'Deadlock detection'),
      ("C", 'Deadlock avoidance'),
      ("D", 'Deadlock recovery')], "C", "Operating Systems"),
    ('Which of the following is a non-preemptive scheduling algorithm?',
     [("A", 'Round Robin'),
      ("B", 'Shortest Job Next'),
      ("C", 'Priority Scheduling'),
      ("D", 'First-Come, First-Served')], "D", "Operating Systems"),
    ('Which software quality metrics improve development and maintenance activities?',
     [("A", 'Process metrics'),
      ("B", 'Project metrics'),
      ("C", 'Product metrics'),
      ("D", 'User metrics')], "C", "Software Engineering"),
    ('What is "black box" testing?',
     [("A", 'System testing'),
      ("B", 'Integration testing'),
      ("C", 'Testing with knowledge of internal structure'),
      ("D", 'Testing without knowledge of internal structure')], "D", "Software Engineering"),
    ('Software Development Life Cycle (SDLC) primarily refers to:',
     [("A", 'Hardware design process'),
      ("B", 'Phases of software creation and maintenance'),
      ("C", 'Testing only'),
      ("D", 'Database management')], "B", "Software Engineering"),
    ('Requirement Analysis ensures:',
     [("A", 'Code optimization'),
      ("B", 'Understanding user needs and system goals'),
      ("C", 'Debugging errors'),
      ("D", 'Writing documentation')], "B", "Software Engineering"),
    ('In Software Design, modularity means:',
     [("A", 'Combining all functions into one block'),
      ("B", 'Dividing system into independent modules'),
      ("C", 'Ignoring user requirements'),
      ("D", 'Using only object-oriented programming')], "B", "Software Engineering"),
    ('Software Maintenance involves:',
     [("A", 'Only fixing bugs after release'),
      ("B", 'Enhancing, adapting, and correcting software post-deployment'),
      ("C", 'Writing new software from scratch'),
      ("D", 'Ignoring user feedback')], "B", "Software Engineering"),
    ('Requirements Engineering mainly acts as a bridge between_______.',
     [("A", 'Developers and testers'),
      ("B", 'Hardware and software'),
      ("C", 'Stakeholders and developers'),
      ("D", 'Users and databases')], "C", "Software Engineering"),
    ('Requirements Engineering contributes to project success mainly by:',
     [("A", 'Reducing hardware costs'),
      ("B", 'Clarifying expectations early'),
      ("C", 'Increasing programming speed'),
      ("D", 'Eliminating documentation')], "B", "Software Engineering"),
    ('Why the role of Requirements Engineering continues throughout the project?',
     [("A", 'Requirements never change'),
      ("B", 'Developers request it'),
      ("C", 'Stakeholder needs may evolve'),
      ("D", 'Testing depends on it')], "C", "Software Engineering"),
    ('When the scope creep occurs?',
     [("A", 'Requirements are well managed'),
      ("B", 'Changes are controlled'),
      ("C", 'Requirements increase without control'),
      ("D", 'Testing is delayed')], "C", "Software Engineering"),
    ('Which of the following best explains why Requirements Engineering is iterative?',
     [("A", 'Testing occurs repeatedly'),
      ("B", 'Stakeholder needs evolve over time'),
      ("C", 'Code refactoring is required'),
      ("D", 'Tools change frequently')], "B", "Software Engineering"),
    ('Which artifact best represents architectural decisions?',
     [("A", 'Source code'),
      ("B", 'UML class diagram'),
      ("C", 'Architecture documentation'),
      ("D", 'Test cases')], "C", "Software Architecture"),
    ('Which pattern decouples sender and receiver?',
     [("A", 'Observer'),
      ("B", 'Mediator'),
      ("C", 'Strategy'),
      ("D", 'Template')], "B", "Software Architecture"),
    ('The MAIN purpose of software architecture is to:',
     [("A", 'Write efficient code'),
      ("B", 'Guide system development and evolution'),
      ("C", 'Replace design patterns'),
      ("D", 'Eliminate testing')], "B", "Software Architecture"),
    ('The Singleton pattern ensures:',
     [("A", 'Multiple instances of a class'),
      ("B", 'Only one instance of a class'),
      ("C", 'No instances of a class'),
      ("D", 'Unlimited instances of a class')], "B", "Software Architecture"),
    ('Which of the following is a non-functional requirement in software architecture?',
     [("A", 'User authentication'),
      ("B", 'Performance'),
      ("C", 'Data validation'),
      ("D", 'Business rules')], "B", "Software Architecture"),
    ('High cohesion and low coupling in software design lead to:',
     [("A", 'Complex and rigid systems'),
      ("B", 'Maintainable and flexible systems'),
      ("C", 'Faster compilation'),
      ("D", 'Larger memory usage')], "B", "Project Management"),
    ('Which management activity is most critical when the team lead suddenly resigns during the "Execution" phase?',
     [("A", 'Configuration Management'),
      ("B", 'Risk Mitigation'),
      ("C", 'Requirement Validation'),
      ("D", 'Perfective Maintenance')], "B", "Project Management"),
    ('The team is using a "Scrum" framework. During the Sprint Review, the customer realizes the UI is not intuitive. Which SPM document was likely poorly defined at the start?',
     [("A", 'Software Requirement Specification (SRS)'),
      ("B", 'Work Breakdown Structure (WBS)'),
      ("C", 'Project Charter'),
      ("D", 'Risk Register')], "A", "Project Management"),
    ('A PM decides to skip Regression Testing to save time. Which maintenance type will likely see the highest increase in the first month after release?',
     [("A", 'Corrective Maintenance'),
      ("B", 'Adaptive Maintenance'),
      ("C", 'Perfective Maintenance'),
      ("D", 'Preventive Maintenance')], "A", "Project Management"),
    ('The "COCOMO" model is used for:',
     [("A", 'Risk Analysis'),
      ("B", 'Software Cost Estimation'),
      ("C", 'Quality Control'),
      ("D", 'Human Resource Management')], "B", "Project Management"),
    ("If a project manager adds a 'Lag' of 3 days between two activities, what does this represent?",
     [("A", 'A period where activities can overlap.'),
      ("B", 'The duration of the critical path'),
      ("C", 'The time needed to hire new resources'),
      ("D", 'A directed delay that must occur before the successor can start')], "D", "Software Testing"),
    ('A software team is developing an e-commerce website and wants to validate whether all payment options function correctly. What type of testing should be conducted?',
     [("A", 'System Testing'),
      ("B", 'Acceptance Testing'),
      ("C", 'Functional Testing'),
      ("D", 'Performance Testing')], "C", "Software Testing"),
    ('Using the ISO/IEC 25010 quality model, a tester is evaluating how easily a new user can learn to navigate the system without reading a manual. Which quality characteristic is the focus of this evaluation?',
     [("A", 'Functional Suitability'),
      ("B", 'Performance Efficiency'),
      ("C", 'Usability'),
      ("D", 'Maintainability')], "C", "Software Testing"),
    ('In a software audit, you find "Message Chains" (e.g., a.getB().getC().doSomething()). What is the evaluation of this pattern?',
     [("A", 'It is an efficient way to navigate object graphs.'),
      ("B", 'It violates the Law of Demeter, making the client coupled to the intermediate structure.'),
      ("C", 'It ensures that all objects are properly synchronized in a multi-threaded environment.'),
      ("D", 'It reduces the number of parameters needed in method calls')], "B", "Software Testing"),
    ('If a system has 100,000 LOC and the Annual Change Traffic (ACT) is 10%, how many lines of code are analyzed for modification annually?',
     [("A", '1,000 LOC'),
      ("B", '10,000 LOC'),
      ("C", '90,000 LOC'),
      ("D", '100,000 LOC')], "B", "Software Testing"),
    ('After a patch to the Invoice module, you also test the payroll module to check for side effects. What is this called?',
     [("A", 'Sanity Testing'),
      ("B", 'Regression Testing'),
      ("C", 'Unit Testing'),
      ("D", 'Alpha Testing')], "B", "Software Maintenance"),
    ('Exit Criteria define:',
     [("A", 'When testing can start'),
      ("B", 'When testing can stop'),
      ("C", 'Test environment setup'),
      ("D", 'Bug severity levels')], "B", "Software Maintenance"),
    ('Black-box Testing focuses on:',
     [("A", 'Internal code structure'),
      ("B", 'System outputs for given inputs'),
      ("C", 'Developer coding style'),
      ("D", 'Memory usage')], "B", "Software Maintenance"),
    ('Which maintenance category involves updating software to improve its performance or maintainability without changing its functional behavior?',
     [("A", 'Corrective'),
      ("B", 'Perfective'),
      ("C", 'Adaptive'),
      ("D", 'Reactive')], "B", "Software Maintenance"),
    ('To perform "Reverse Engineering" on a legacy system without documentation, which artifact is synthesized first to understand the control flow?',
     [("A", 'The Database Schema'),
      ("B", 'Call Graphs or Control Flow Graphs (CFG)'),
      ("C", 'The User Manual'),
      ("D", 'The Marketing Requirement Document')], "B", "Software Maintenance"),
    ('Which of the following is a private IP address?',
     [("A", '8.8.8.8'),
      ("B", '192.168.1.1'),
      ("C", '172.15.10.10'),
      ("D", '169.254.0.1')], "B", "Networking"),
    ('What is the primary purpose of the DHCP protocol?',
     [("A", 'To resolve domain names to IP addresses'),
      ("B", 'To assign IP addresses dynamically to devices'),
      ("C", 'To route packets between networks'),
      ("D", 'To detect errors in data transmission')], "B", "Networking"),
    ('Which device operates at the Data Link Layer of the OSI model?',
     [("A", 'Router'),
      ("B", 'Switch'),
      ("C", 'Hub'),
      ("D", 'Repeater')], "B", "Networking"),
    ('What is the main disadvantage of a bus topology?',
     [("A", 'High cost of implementation'),
      ("B", 'Difficulty in troubleshooting'),
      ("C", 'Single point of failure'),
      ("D", 'Limited scalability')], "C", "Networking"),
    ('What is the purpose of an access control list (ACL)?',
     [("A", 'To define permissions for users and devices in a network'),
      ("B", 'To log security incidents'),
      ("C", 'To encrypt network traffic'),
      ("D", 'To detect malware infections')], "A", "Networking"),
    ('Which security principle ensures that only authorized users have access to sensitive data?',
     [("A", 'Availability'),
      ("B", 'Confidentiality'),
      ("C", 'Integrity'),
      ("D", 'non-repudiation')], "B", "Security"),
    ('Which type of attack aims to disrupt normal traffic on a network by overwhelming it with a flood of data?',
     [("A", 'Phishing'),
      ("B", 'Man-in-the-Middle'),
      ("C", 'Denial-of-Service (DoS)'),
      ("D", 'SQL Injection')], "C", "Security"),
    ('In the TCP/IP model, which layer corresponds to the Network Layer in the OSI model?',
     [("A", 'Application Layer'),
      ("B", 'Transport Layer'),
      ("C", 'Internet Layer'),
      ("D", 'Network Access Layer')], "C", "Networking"),
    ('Which protocol operates at the Transport Layer of the OSI model?',
     [("A", 'IP'),
      ("B", 'TCP'),
      ("C", 'ARP'),
      ("D", 'HTTP')], "B", "Networking"),
    ('What is the default subnet mask for a Class B IP address?',
     [("A", '255.0.0.0'),
      ("B", '255.255.0.0'),
      ("C", '255.255.255.0'),
      ("D", '255.255.255.255')], "B", "Networking"),
    ('Which layer handles reliable data transfer with error detection?',
     [("A", 'Physical'),
      ("B", 'Data Link'),
      ("C", 'Transport'),
      ("D", 'Application')], "C", "Networking"),
    ('Which type of malware disguises itself as legitimate software?',
     [("A", 'Worm'),
      ("B", 'Trojan Horse'),
      ("C", 'Spyware'),
      ("D", 'Rootkit')], "B", "Security"),
    ('Which approach updates probabilities using prior knowledge and new evidence?',
     [("A", 'Fuzzy Logic'),
      ("B", 'Frequentist Approach'),
      ("C", 'Bayesian Inference'),
      ("D", 'Deterministic Models')], "C", "AI / ML"),
    ('Which agent deals with happy and unhappy states?',
     [("A", 'Simple reflex agent'),
      ("B", 'Model based agent'),
      ("C", 'Learning agent'),
      ("D", 'Utility based agent')], "D", "AI / ML"),
    ('Which of the following best defines Artificial Intelligence?',
     [("A", 'Programming computers with fixed rules'),
      ("B", 'Making machines mimic human intelligence'),
      ("C", 'Designing faster hardware'),
      ("D", 'Automating repetitive tasks only')], "B", "AI / ML"),
    ('Which branch of Artificial Intelligence deals with learning from data?',
     [("A", 'Machine Learning'),
      ("B", 'Expert Systems'),
      ("C", 'Natural Language Processing'),
      ("D", 'Computer Vision')], "A", "AI / ML"),
    ('The Turing Test is used to evaluate:',
     [("A", 'System performance'),
      ("B", 'Human-computer interaction'),
      ("C", 'Machine intelligence'),
      ("D", 'Algorithm efficiency')], "C", "AI / ML"),
    ('Which AI technique uses symbols and rules to represent knowledge?',
     [("A", 'Neural Networks'),
      ("B", 'Knowledge Representation'),
      ("C", 'Genetic Algorithms'),
      ("D", 'Reinforcement Learning')], "B", "AI / ML"),
    ('In search algorithms, which strategy explores the shallowest nodes first?',
     [("A", 'Depth-First Search'),
      ("B", 'Breadth-First Search'),
      ("C", 'Best-First Search'),
      ("D", 'Hill Climbing')], "B", "AI / ML"),
    ('In Artificial Intelligence, which approach is commonly used to handle uncertainty in reasoning?',
     [("A", 'Deterministic algorithms'),
      ("B", 'Probabilistic reasoning'),
      ("C", 'Symbolic logic only'),
      ("D", 'Greedy search')], "B", "AI / ML"),
    ('In A* search, the evaluation function is:',
     [("A", 'f(n) = g(n)'),
      ("B", 'f(n) = h(n)'),
      ("C", 'f(n) = g(n) + h(n)'),
      ("D", 'f(n) = g(n) − h(n)')], "C", "AI / ML"),
]

assert len(RAW) == 100, f"Expected 100 questions, got {len(RAW)}"
