"""High-quality cognitive-tagged banks for predicted 2018 exams (v2 and v3)."""

from exam2018_cognitive import q, validate_bank
from exam2018_data import TOPIC_COUNTS as TOPIC_COUNTS_V2

TOPIC_COUNTS_V3 = {
    "Fundamentals of Programming": 7,
    "C++": 4,
    "Data Structures": 6,
    "Java / OOP": 5,
    "Web Development": 9,
    "Android": 5,
    "Database": 6,
    "Operating Systems": 6,
    "Software Engineering": 16,
    "Software Architecture": 5,
    "Project Management": 5,
    "Software Testing": 5,
    "Networking": 6,
    "Security": 5,
    "AI / ML": 10,
}


# fmt: off
BANK_V2 = [
    # Fundamentals of Programming (5)
    q("Fundamentals of Programming", "Which statement correctly distinguishes a compiler from an interpreter?",
      ["A compiler translates the whole program before execution", "An interpreter always produces object files", "A compiler executes one line at a time", "An interpreter cannot report runtime errors"], "A", "Compiler vs interpreter behavior", "Remember"),
    q("Fundamentals of Programming", "Why is pseudocode often written before coding a new payroll module?",
      ["It helps clarify algorithm logic before language-specific syntax", "It automatically creates a database schema", "It replaces unit testing completely", "It guarantees zero defects in production"], "A", "Role of pseudocode in design", "Understand"),
    q("Fundamentals of Programming", "Why should a loop termination condition be reviewed during desk-checking?",
      ["To verify that iteration eventually stops for valid input ranges", "To ensure CPU fan speed remains constant", "To avoid writing function headers", "To force all variables to be global"], "A", "Desk-checking loop correctness", "Understand"),
    q("Fundamentals of Programming", "A fee calculation uses: if mark >= 50 then pass else fail. What is the result when mark = 50?",
      ["pass", "fail", "runtime error", "undefined"], "A", "Trace simple selection", "Apply"),
    q("Fundamentals of Programming", "Given x = 3, y = 5, then x = x + y; y = x - y; x = x - y;. What are final values?",
      ["x=3, y=5", "x=5, y=3", "x=8, y=2", "x=2, y=8"], "B", "Trace variable updates", "Apply"),

    # C++ (4)
    q("C++", "Which declaration is valid in C++?",
      ["int 2count = 10;", "float total_mark = 72.5f;", "char name[] = 'Abel';", "string class = \"SE\";"], "B", "Valid identifier and literal forms", "Remember"),
    q("C++", "Why is pass-by-reference used in a function that updates an account balance?",
      ["Because it allows the called function to modify the caller's variable", "Because it prevents all side effects", "Because references use less memory than every primitive", "Because it avoids function declarations"], "A", "Reference semantics", "Understand"),
    q("C++", "What is printed by: int s=0; for(int i=1;i<=3;i++) s+=i; cout<<s;",
      ["3", "6", "9", "12"], "B", "Loop output trace", "Apply"),
    q("C++", "A team must produce two variants of an invoicing feature for desktop and kiosk using shared core logic. Which C++ approach best supports this?",
      ["Use inheritance with virtual functions for variant-specific behavior", "Copy-paste separate programs without shared interfaces", "Store UI code in global variables", "Avoid classes and use only goto"], "A", "Design extensible polymorphic solution", "Create"),

    # Data Structures (6)
    q("Data Structures", "Why does BFS use a queue instead of a stack?",
      ["Because BFS explores nodes level by level in first-in-first-out order", "Because stacks are faster than queues for all graphs", "Because queues remove duplicate vertices automatically", "Because BFS never stores discovered nodes"], "A", "BFS traversal rationale", "Create"),
    q("Data Structures", "A call-center system must process the earliest waiting ticket first. Which structure fits best?",
      ["Stack", "Queue", "Binary search tree", "Hash set"], "B", "Select structure by operation semantics", "Apply"),
    q("Data Structures", "For sorted array [4, 8, 15, 16, 23, 42], what index (0-based) is found by binary search for 16?",
      ["2", "3", "4", "5"], "B", "Binary search trace", "Apply"),
    q("Data Structures", "For graph edges A-B, A-C, B-D, C-E, starting at A and visiting neighbors alphabetically, what is BFS order?",
      ["A, B, D, C, E", "A, C, E, B, D", "A, B, C, D, E", "A, D, B, E, C"], "C", "Analyze traversal order", "Analyze"),
    q("Data Structures", "An algorithm performs two nested loops over n elements and does constant work inside. What is time complexity?",
      ["O(log n)", "O(n)", "O(n log n)", "O(n^2)"], "D", "Reason about asymptotic complexity", "Analyze"),
    q("Data Structures", "You need undo/redo in a drawing app used in a computer lab. What is the best data-structure design?",
      ["Use two stacks: one for undo and one for redo", "Use a single queue only", "Use adjacency matrix", "Use hash map with random deletions"], "A", "Create practical design from ADT concepts", "Create"),

    # Java / OOP (6)
    q("Java / OOP", "Which Java keyword prevents a subclass from overriding a method?",
      ["abstract", "protected", "final", "native"], "C", "Keyword recall", "Remember"),
    q("Java / OOP", "Why is encapsulation important in a student registration class?",
      ["It protects object state and enforces access through methods", "It removes the need for constructors", "It forces all fields to be public", "It prevents code reuse"], "A", "Encapsulation purpose", "Understand"),
    q("Java / OOP", "What is output? int x=5; System.out.println(++x + x++);",
      ["10", "11", "12", "13"], "C", "Java expression trace", "Apply"),
    q("Java / OOP", "Given class Animal {sound()} and Dog extends Animal overriding sound(), what is printed by Animal a = new Dog(); a.sound(); when Dog prints \"Bark\"?",
      ["Compile error", "Animal sound", "Bark", "null"], "C", "Dynamic dispatch trace", "Apply"),
    q("Java / OOP", "A program catches Exception before NumberFormatException. What issue occurs?",
      ["Specific exception block becomes unreachable", "Program runs faster", "All checked exceptions disappear", "JVM disables stack traces"], "A", "Analyze exception hierarchy effect", "Analyze"),
    q("Java / OOP", "A university wants a grading platform that supports adding new grading policies without editing existing policy classes. Which design is best?",
      ["Use Strategy pattern with a common GradePolicy interface", "Put all policies in one 700-line switch statement", "Duplicate grading code per department", "Use static global flags in one class"], "A", "Design extensible OOP solution", "Create"),

    # Web Development (7)
    q("Web Development", "Why is POST preferred over GET for login credentials?",
      ["POST sends credentials in message body rather than URL query string", "GET cannot reach a server", "POST is always encrypted without HTTPS", "GET cannot return status codes"], "A", "HTTP method choice reasoning", "Create"),
    q("Web Development", "Why should server-side input validation still be done even if HTML form validation exists?",
      ["Client-side validation can be bypassed by crafted requests", "Browsers always block malicious input", "Server-side checks reduce availability", "Validation is only for CSS errors"], "A", "Defense-in-depth for web inputs", "Understand"),
    q("Web Development", "A REST endpoint `/students/45` receives a request to update the whole student resource idempotently. Which method is most suitable?",
      ["POST", "GET", "PUT", "OPTIONS"], "C", "Choose HTTP verb for scenario", "Understand"),
    q("Web Development", "A page should load dashboard data without full reload when a filter changes. Which browser technique is most appropriate?",
      ["Synchronous form submission each change", "AJAX/fetch asynchronous request", "HTML comments", "FTP upload"], "B", "Apply asynchronous web update", "Apply"),
    q("Web Development", "An endpoint sometimes returns 500 under high load, while static files still serve normally. Which is the most likely analysis?",
      ["Application/server-side processing path is failing, not the CDN for static assets", "DNS must be deleting routes", "Client browser cache is corrupt for all users", "HTTP status code 500 means redirect"], "A", "Analyze failure by HTTP evidence", "Analyze"),
    q("Web Development", "A college portal team must choose one approach for authentication state: localStorage token without expiry, or HttpOnly secure cookie session with rotation and CSRF protection. Which is best?",
      ["HttpOnly secure cookie session with rotation and CSRF protection", "Store plain token in URL query for convenience", "Disable logout to avoid session mismatch", "Use GET for password submission"], "A", "Evaluate secure web session decision", "Evaluate"),
    q("Web Development", "Design the best URL scheme for course resources in a REST API.",
      ["Use nouns and hierarchy like /departments/{id}/courses/{id}/resources", "Use one endpoint /doEverythingNow", "Use RPC verbs in path for every action", "Use random path per deployment"], "A", "Create coherent REST resource model", "Create"),

    # Android (5)
    q("Android", "Why is long-running network sync implemented in a WorkManager/Service instead of an Activity?",
      ["Activities can be destroyed when users leave the screen", "Services cannot use network APIs", "Activities always run in background forever", "Only Activities can receive Intents"], "A", "Component lifecycle reasoning", "Understand"),
    q("Android", "An app must open a detail screen and pass `studentId=3021`. Which mechanism is correct?",
      ["BroadcastReceiver with no extras", "Intent extra passed to target Activity", "Manifest metadata only", "Gradle build variant"], "B", "Apply Intent extras", "Apply"),
    q("Android", "A team can choose either to request broad storage permission for convenience or use scoped storage and least privilege. Which is better for a university app?",
      ["Use scoped storage and least privilege", "Request all dangerous permissions by default", "Disable runtime permissions", "Store records in shared public folders"], "A", "Evaluate Android privacy trade-off", "Evaluate"),
    q("Android", "Design an offline-first attendance app for schools with unstable internet. Which plan is best?",
      ["Store attendance locally with Room and sync in background when connectivity returns", "Write records only to remote API and discard on failure", "Clear local data after every screen rotation", "Use Toast messages as persistence"], "A", "Create resilient Android data flow", "Create"),
    q("Android", "Create the best architecture for maintainable Android UI and data layers.",
      ["Use MVVM with Repository and clear state flows", "Put networking, SQL, and UI in one Activity", "Use global mutable static variables for all data", "Remove ViewModel to simplify lifecycle"], "A", "Create maintainable architecture", "Create"),

    # Database (6)
    q("Database", "Why does normalization reduce update anomalies in a registration database?",
      ["It separates entities so one fact is stored in one place", "It stores all attributes in one giant table", "It removes all foreign keys", "It requires denormalizing every query"], "A", "Understand anomaly prevention", "Create"),
    q("Database", "Given Student(sid, name, dept) and Enroll(sid, cid, score), which SQL returns names of students scoring above 80 in course 'SE401'?",
      ["SELECT name FROM Student s JOIN Enroll e ON s.sid=e.sid WHERE e.cid='SE401' AND e.score>80", "SELECT * FROM Enroll WHERE name>80", "UPDATE Student SET score=80", "DELETE FROM Student WHERE cid='SE401'"], "A", "Apply SQL join with condition", "Apply"),
    q("Database", "Given Orders(order_id, customer_id, amount), which query returns total amount per customer?",
      ["SELECT customer_id, SUM(amount) FROM Orders GROUP BY customer_id", "SELECT SUM(customer_id) FROM Orders", "SELECT amount FROM Orders WHERE GROUP BY customer_id", "SELECT customer_id FROM Orders HAVING amount"], "A", "Apply aggregation query", "Apply"),
    q("Database", "A table stores both student and department phone repeatedly in each enrollment row. What anomaly is most likely?",
      ["Insertion/update anomaly due to redundancy", "No anomaly because duplicates improve integrity", "Deadlock anomaly at network layer", "Compilation anomaly"], "A", "Analyze ER/relational anomaly", "Analyze"),
    q("Database", "A team can denormalize heavily for read speed or keep normalized schema with targeted indexes for mixed read/write workloads. Which is the best default choice?",
      ["Keep normalized schema and add targeted indexes", "Denormalize everything first without profiling", "Use CSV files instead of DBMS", "Disable constraints for faster inserts"], "A", "Evaluate design trade-off", "Evaluate"),
    q("Database", "Create the best schema strategy for storing exam attempts and answers with auditability.",
      ["Separate Attempt, AttemptItem, and Answer tables with foreign keys and timestamps", "Store entire exam JSON in one text column only", "Use one table with repeated comma-separated values", "Use random file names as primary keys without relations"], "A", "Create robust relational schema", "Create"),

    # Operating Systems (6)
    q("Operating Systems", "Why does round-robin scheduling improve responsiveness for interactive users compared with FCFS?",
      ["It gives each process a time slice and rotates quickly", "It runs only system processes", "It removes context switching", "It always minimizes completion time"], "A", "Understand scheduling behavior", "Understand"),
    q("Operating Systems", "Given process burst times P1=4, P2=3, P3=2 and FCFS order P1,P2,P3, what is average waiting time?",
      ["1", "2", "11/3", "5"], "C", "Apply FCFS waiting-time calculation", "Apply"),
    q("Operating Systems", "In a system with 4 page frames, a process references more pages than memory can hold. Which mechanism allows execution?",
      ["Virtual memory with paging", "Only static linking", "Disable swap and continue", "Compile with optimization -O3"], "A", "Apply VM concept to scenario", "Apply"),
    q("Operating Systems", "P1 holds R1 and waits for R2; P2 holds R2 and waits for R1. Which deadlock condition pattern is observed?",
      ["Circular wait with hold-and-wait", "No preemption removed", "Starvation only", "Thrashing only"], "A", "Analyze deadlock scenario", "Analyze"),
    q("Operating Systems", "Which effect indicates thrashing?",
      ["CPU utilization drops while page fault rate rises sharply", "Disk usage drops to zero", "All threads complete faster", "Context switches become impossible"], "A", "Analyze memory pressure behavior", "Analyze"),
    q("Operating Systems", "A university lab can either disable swap to avoid disk wear or tune working sets and page replacement. Which is better?",
      ["Tune working sets and page replacement while keeping swap policy", "Disable virtual memory entirely", "Run one process at a time", "Use FIFO for all workloads regardless"], "A", "Evaluate OS memory policy", "Create"),

    # Software Engineering (16)
    q("Software Engineering", "Why should non-functional requirements be specified early in the SRS?",
      ["They drive architecture and test acceptance criteria", "They are optional after coding finishes", "They only matter to UI designers", "They are identical to source code comments"], "A", "Understand NFR importance", "Understand"),
    q("Software Engineering", "Why is requirements traceability valuable during maintenance?",
      ["It links changes to originating stakeholder needs and tests", "It removes need for version control", "It prevents all requirement changes", "It replaces defect tracking"], "A", "Understand traceability purpose", "Understand"),
    q("Software Engineering", "Why is iterative development preferred when stakeholder needs are evolving?",
      ["It enables feedback-driven refinement each increment", "It guarantees zero rework", "It removes planning activities", "It forbids automated testing"], "A", "Understand iterative rationale", "Understand"),
    q("Software Engineering", "Why is code review effective in reducing defects before release?",
      ["It catches logic and maintainability issues early", "It eliminates need for testing and QA", "It replaces user acceptance testing", "It guarantees performance goals"], "A", "Understand review value", "Create"),
    q("Software Engineering", "A requirement says, 'System should be very fast.' What is the best rewrite?",
      ["System shall return search results within 2 seconds for 95% of requests", "System shall be fast enough", "System shall use modern hardware", "System should try to be responsive"], "A", "Apply measurable requirement writing", "Apply"),
    q("Software Engineering", "A bug repeatedly reappears after merges. Which practice most directly prevents this?",
      ["Automated regression tests in CI", "Manual demo before semester end", "Long-lived branches without rebasing", "Skipping unit tests for speed"], "A", "Apply engineering practice", "Apply"),
    q("Software Engineering", "A team delivers quickly by bypassing design and tests, then maintenance cost grows each sprint. What is this pattern?",
      ["Technical debt accumulation", "Perfective maintenance success", "Feature toggling", "Parallel development"], "A", "Analyze process consequences", "Understand"),
    q("Software Engineering", "A project manager can shorten schedule by reducing testing week or reducing scope of low-value reports after stakeholder review. Which is better?",
      ["Reduce low-value scope while preserving quality gates", "Reduce testing week first", "Skip requirements review", "Freeze bug fixes"], "A", "Evaluate scope-time-quality trade-off", "Evaluate"),
    q("Software Engineering", "Design a practical change control workflow for requirements in a ministry project.",
      ["Submit change request, impact analysis, CCB decision, update baselines and tests", "Allow any developer to edit scope in production", "Reject all changes by default", "Update code first and document later"], "A", "Create governance workflow", "Create"),
    q("Software Engineering", "Create the best branching strategy for a student portal with weekly releases and urgent hotfixes.",
      ["Use trunk-based development with short-lived branches and hotfix path", "Use one branch per developer forever", "Commit directly to production server", "Disable pull requests"], "A", "Create release-friendly workflow", "Create"),
    q("Software Engineering", "Create an effective definition of done for a feature team.",
      ["Code reviewed, tests passing, docs updated, acceptance criteria met", "Feature compiles on one laptop", "PO says maybe", "Merged without tests if urgent"], "A", "Create quality criteria", "Create"),
    q("Software Engineering", "Create a maintainability plan for a legacy module with high defect density.",
      ["Refactor incrementally behind tests and track defect trends", "Rewrite all modules at once without tests", "Freeze all changes permanently", "Delete documentation"], "A", "Create improvement plan", "Create"),
    q("Software Engineering", "Create the most suitable elicitation approach for dispersed stakeholders across regions.",
      ["Combine structured interviews, workshops, and prototype reviews", "Collect requirements from one developer only", "Use assumptions from previous project", "Skip validation to save travel"], "A", "Create elicitation strategy", "Create"),
    q("Software Engineering", "Create a metrics set to monitor release health over time.",
      ["Lead time, change failure rate, defect escape rate, MTTR", "Number of comments in code", "CPU model name", "Wi-Fi signal strength"], "A", "Create actionable engineering metrics", "Create"),
    q("Software Engineering", "A senior engineer finds a severe privacy bug two days before release. What is the most ethical action?",
      ["Escalate immediately, document risk, and block release until mitigated", "Hide the bug to protect schedule", "Ship and fix only if users complain", "Delete issue tracker entry"], "A", "Professional ethics in SE", "Affective"),
    q("Software Engineering", "During sprint planning, two developers disagree strongly on design. What behavior best supports team effectiveness?",
      ["Use evidence-based discussion and seek consensus on criteria", "Ignore one side and proceed silently", "Escalate personal attacks", "Delay until deadline pressure decides"], "A", "Constructive teamwork behavior", "Affective"),

    # Software Architecture (5)
    q("Software Architecture", "Why is layered architecture commonly used for enterprise information systems?",
      ["It separates concerns and controls dependencies between layers", "It requires no interfaces", "It removes the need for deployment planning", "It stores all logic in database triggers"], "A", "Understand layered architecture", "Understand"),
    q("Software Architecture", "A system must integrate legacy modules quickly. Should the team choose event-driven microservices now or begin with a modular monolith and clear boundaries?",
      ["Begin with modular monolith and evolve where needed", "Adopt microservices immediately for every module", "Rewrite all code in assembly", "Avoid architecture decisions"], "A", "Evaluate architecture migration strategy", "Evaluate"),
    q("Software Architecture", "Create a service decomposition for university management platform.",
      ["Admissions, Course Catalog, Registration, Billing, and Notification services with clear APIs", "One giant service with shared global tables", "Separate service per controller method", "No API contracts between components"], "A", "Create bounded-context decomposition", "Create"),
    q("Software Architecture", "Design an architecture pattern for high read traffic to course catalogs with occasional updates.",
      ["Use cache-aside with invalidation and authoritative DB", "Write-through to local text files only", "Disable caching entirely always", "Store state only in browser memory"], "A", "Create scalable read architecture", "Create"),
    q("Software Architecture", "Create the best approach for cross-cutting observability in distributed services.",
      ["Centralized logging, metrics, tracing, and correlation IDs", "Print stack traces only on client browser", "Disable logs in production permanently", "Rely on manual screenshots for diagnosis"], "A", "Create observability architecture", "Create"),

    # Project Management (6)
    q("Project Management", "Why is a Work Breakdown Structure prepared before detailed scheduling?",
      ["It decomposes deliverables into manageable work packages", "It replaces risk management plans", "It is only needed after deployment", "It estimates server CPU usage"], "A", "Understand WBS role", "Understand"),
    q("Project Management", "A project has activities A(2d), B(3d) after A, and C(4d) after A; D(2d) after B and C. What is project duration?",
      ["7 days", "8 days", "9 days", "11 days"], "B", "Apply critical path calculation", "Apply"),
    q("Project Management", "A donor offers to add scope without extending deadline or budget. Which decision is best?",
      ["Negotiate trade-offs and re-baseline formally", "Accept silently and pressure team overtime indefinitely", "Drop QA activities first", "Ignore sponsor communication"], "A", "Evaluate PM trade-off", "Affective"),
    q("Project Management", "Create a WBS for deploying an online exam system nationally.",
      ["Initiation, Requirements, Development, Pilot, Training, Rollout, Support", "Coding, Coding, Coding only", "Procure laptops then finish", "Launch without readiness checks"], "A", "Create structured WBS", "Create"),
    q("Project Management", "Create a risk response plan for internet outages during computer-based exams.",
      ["Define mitigation, contingency, owner, trigger, and communication path", "Assume outages will not occur", "Remove all deadlines", "Stop documenting risks"], "A", "Create risk management plan", "Create"),
    q("Project Management", "A team member is new to test automation and repeatedly misses tasks. What is the most constructive leadership response?",
      ["Coach, pair with mentor, and adjust plan transparently", "Publicly shame the member in meetings", "Hide delays from stakeholders", "Reassign all work without feedback"], "A", "Supportive leadership behavior", "Affective"),

    # Software Testing (5)
    q("Software Testing", "Why is boundary value analysis effective for numeric input fields?",
      ["Defects frequently occur near minimum and maximum limits", "It only tests random interior values", "It replaces exploratory testing", "It is valid only for UI colors"], "A", "Understand BVA rationale", "Understand"),
    q("Software Testing", "For allowed age range 18-60 inclusive, which set is best for boundary testing?",
      ["17, 18, 19, 59, 60, 61", "1, 20, 40, 80", "18 only", "60 only"], "A", "Apply BVA case design", "Understand"),
    q("Software Testing", "A feature passes unit tests but fails when combined with payment gateway and message queue. Which test level exposed this?",
      ["Integration testing", "Mutation testing", "Usability testing", "Smoke testing only"], "A", "Analyze failure location by test level", "Analyze"),
    q("Software Testing", "Create a lean but effective test plan for semester registration peak week.",
      ["Prioritize critical paths, define entry/exit criteria, data sets, and rollback checks", "Test only login page", "Run tests after release only", "Skip performance scenarios"], "A", "Create risk-based test plan", "Create"),
    q("Software Testing", "Create the best strategy to prevent recurring production bugs.",
      ["Automate regression suite and include bug reproduction tests in CI", "Delete failed tests to keep pipeline green", "Run tests manually once per year", "Allow direct commits to main"], "A", "Create sustainable QA approach", "Create"),

    # Networking (7)
    q("Networking", "Why are subnet masks used in IPv4 networks?",
      ["To separate network and host portions for routing", "To encrypt all packets", "To replace DNS", "To increase CPU clock speed"], "A", "Understand subnet mask role", "Understand"),
    q("Networking", "How many usable host addresses are in a /27 subnet?",
      ["30", "32", "62", "14"], "A", "Apply subnet calculation", "Apply"),
    q("Networking", "A campus has network 192.168.10.0/24 and needs 4 equal subnets. What new prefix is required?",
      ["/25", "/26", "/27", "/28"], "B", "Apply subnetting by equal division", "Apply"),
    q("Networking", "A packet from host in VLAN 10 to VLAN 20 requires which device function?",
      ["Layer-2 switching only", "Inter-VLAN routing at Layer 3", "DNS recursion", "NAT exemption"], "B", "Analyze routed path requirements", "Understand"),
    q("Networking", "Design a resilient network for a regional exam center with two ISPs and critical online proctoring.",
      ["Use dual WAN with failover routing and health checks", "Use one ISP and manual tethering only", "Disable routing protocols", "Use unmanaged hubs everywhere"], "A", "Create resilient network design", "Create"),
    q("Networking", "Create an addressing plan for 6 departments each requiring about 40 hosts.",
      ["Allocate /26 per department from a summarizable block", "Use /30 per department", "Give all departments one /24 with no VLANs", "Use random public IPs"], "A", "Create IP addressing strategy", "Create"),
    q("Networking", "A school can deploy unmanaged flat network or segmented VLAN network with ACLs. Which is better for security and manageability?",
      ["Segmented VLAN network with ACLs", "Single flat network for all devices", "No DHCP and manual IP for everyone forever", "Disable gateway redundancy"], "A", "Evaluate network architecture trade-off", "Create"),

    # Security (7)
    q("Security", "Why should passwords be stored using salted adaptive hashing rather than plain SHA256?",
      ["Adaptive hashing slows brute-force and salt prevents rainbow-table reuse", "SHA256 cannot hash strings", "Plain text is easier to audit", "Salting weakens security"], "A", "Understand password storage best practice", "Understand"),
    q("Security", "A phishing email asks lecturers to re-enter portal credentials via a similar-looking domain. Which control most directly reduces account takeover?",
      ["Enable multi-factor authentication", "Disable spam filtering", "Share one account for all lecturers", "Allow password reuse indefinitely"], "A", "Apply phishing mitigation", "Apply"),
    q("Security", "An API receives SQL payload `' OR 1=1 --` in login form. Which fix is most appropriate?",
      ["Use parameterized queries and strict input handling", "Escape spaces only", "Block users with short names", "Hide DB errors without code changes"], "A", "Apply SQL injection defense", "Apply"),
    q("Security", "A server shows many SYN packets from spoofed addresses without completed handshakes. What attack is likely?",
      ["SYN flood denial-of-service", "ARP cache poisoning", "Cross-site scripting", "Directory traversal"], "A", "Analyze network attack signature", "Analyze"),
    q("Security", "A district education office can either allow shared admin accounts or enforce unique named admin accounts with least privilege and logging. Which is best?",
      ["Unique named admin accounts with least privilege and logging", "Shared admin account for convenience", "Disable log retention", "Use default passwords"], "A", "Evaluate access-control governance", "Evaluate"),
    q("Security", "Create a practical incident response workflow for malware on exam lab PCs.",
      ["Detect, isolate hosts, preserve evidence, eradicate, recover, and conduct lessons learned", "Reboot affected systems and ignore logs", "Disconnect internet forever", "Notify users after one month"], "A", "Create IR lifecycle", "Create"),
    q("Security", "A developer accidentally commits an API key to a public repository. What professional response is most responsible?",
      ["Rotate key immediately, report incident, and improve secret-scanning controls", "Leave key active and hope no one notices", "Delete commit history secretly and tell no one", "Share key with team chat for backup"], "A", "Security accountability behavior", "Affective"),

    # AI / ML (9)
    q("AI / ML", "Why can a model perform well on training data but poorly on unseen data?",
      ["It may be overfitting rather than generalizing", "Because gradient descent always fails", "Because labels are never needed", "Because test data must equal training data"], "A", "Understand overfitting", "Understand"),
    q("AI / ML", "Why is feature scaling often required for k-means clustering?",
      ["Distance-based algorithms are sensitive to feature magnitudes", "Scaling removes all outliers automatically", "Scaling converts clustering to classification", "Scaling guarantees perfect clusters"], "A", "Understand scaling rationale", "Understand"),
    q("AI / ML", "A binary classifier predicts fraud. From confusion matrix TP=40, FP=10, FN=20, TN=130, what is precision?",
      ["0.50", "0.67", "0.80", "0.90"], "C", "Apply precision formula", "Apply"),
    q("AI / ML", "A search agent uses A* with admissible heuristic. Which property is expected?",
      ["It finds an optimal path if one exists", "It ignores path cost completely", "It behaves exactly as DFS", "It never expands nodes"], "A", "Apply informed search property", "Apply"),
    q("AI / ML", "Model A has 98% accuracy on imbalanced data where only 2% are positive; recall is 10%. What is key concern?",
      ["High accuracy hides poor minority-class detection", "Model is definitely optimal", "Class imbalance improves recall automatically", "Precision must be 100%"], "A", "Analyze metric interpretation", "Analyze"),
    q("AI / ML", "Create a pipeline for predicting student dropout risk from semester data.",
      ["Data cleaning, feature engineering, train/validation split, model training, fairness checks, monitoring", "Train once and never monitor", "Use test data for tuning", "Ignore missing values"], "A", "Create ML lifecycle pipeline", "Create"),
    q("AI / ML", "Design an NLP assistant for campus FAQs that can improve over time with feedback.",
      ["Combine retrieval over verified docs with feedback loop and periodic evaluation", "Hardcode one response for all questions", "Allow model to answer without any data governance", "Disable evaluation"], "A", "Create practical AI assistant design", "Create"),
    q("AI / ML", "Create an expert-system rule strategy for course advising.",
      ["Represent prerequisite and GPA constraints as if-then rules with explanation output", "Store rules as screenshots", "Remove conflict resolution", "Use random recommendations"], "A", "Create rule-based reasoning solution", "Create"),
    q("AI / ML", "Design the best approach for deploying a model in production with drift risk.",
      ["Use canary rollout, monitor data drift, and trigger retraining policy", "Deploy once and lock forever", "Manually inspect every prediction only", "Disable logging for privacy"], "A", "Create MLOps deployment strategy", "Create"),
]


BANK_V3 = [
    # Fundamentals of Programming (7)
    q("Fundamentals of Programming", "Which concept means solving a problem by breaking it into smaller subproblems with clear steps?",
      ["Algorithmic decomposition", "Memory paging", "Socket tunneling", "UI theming"], "A", "Core problem-solving concept", "Remember"),
    q("Fundamentals of Programming", "Why does modular programming improve teamwork in large projects?",
      ["Different members can own and test independent modules", "It removes need for interfaces", "It forces one person to edit all files", "It prevents integration"], "A", "Understand modularity benefit", "Understand"),
    q("Fundamentals of Programming", "Why should sentinel values be chosen carefully in input loops?",
      ["A sentinel conflicting with valid data can terminate processing incorrectly", "Sentinels speed CPU clock", "Sentinels replace error handling", "Sentinels are required only in recursion"], "A", "Understand loop-control pitfalls", "Understand"),
    q("Fundamentals of Programming", "Given n=4 and loop for(i=1;i<=n;i++) sum+=i*i, what is final sum?",
      ["16", "20", "30", "40"], "C", "Apply loop computation", "Apply"),
    q("Fundamentals of Programming", "An algorithm needs to process each student's mark once and compute average. Which complexity target is most appropriate?",
      ["O(1)", "O(log n)", "O(n)", "O(n^2)"], "C", "Apply complexity to scenario", "Apply"),
    q("Fundamentals of Programming", "A town internet bill formula changed often due to policy updates. Which program structure best supports this?",
      ["Externalize rules into configurable policy module", "Hardcode values in multiple functions", "Use only global variables", "Duplicate billing logic per screen"], "A", "Create adaptable program design", "Create"),
    q("Fundamentals of Programming", "Create the best input-validation flow for exam marks entered by operators.",
      ["Validate range/type, show specific errors, and reject invalid submissions", "Accept all values including text and negatives", "Crash on first invalid record", "Silently round all marks to nearest pass"], "A", "Create robust validation flow", "Create"),

    # C++ (4)
    q("C++", "Which header is needed for `std::vector`?",
      ["<map>", "<vector>", "<array>", "<cstring>"], "B", "C++ standard library recall", "Remember"),
    q("C++", "Why does RAII reduce memory leaks in C++ applications?",
      ["Resources are tied to object lifetime and released automatically", "It disables destructors", "It requires manual free() everywhere", "It avoids constructors"], "A", "Understand RAII", "Understand"),
    q("C++", "What is output? int a=2; int b=3; cout << a*b + b;",
      ["5", "6", "9", "12"], "C", "Apply expression evaluation", "Apply"),
    q("C++", "A codebase has many if/else branches to choose payment processor and grows every semester. What redesign is best?",
      ["Use polymorphic strategy classes selected at runtime", "Keep adding nested if/else blocks", "Use macros for all business logic", "Duplicate function for every campus"], "A", "Create maintainable C++ design", "Create"),

    # Data Structures (6)
    q("Data Structures", "Why is a hash table preferred for checking whether a student ID already exists during batch import?",
      ["Average-case lookup is near O(1)", "It guarantees sorted traversal", "It stores duplicate keys better than sets", "It avoids collisions completely"], "A", "Understand hash lookup benefit", "Understand"),
    q("Data Structures", "A scheduler must always execute the highest-priority task first. Which structure fits?",
      ["Array list", "Priority queue (heap)", "Stack", "Singly linked list"], "B", "Apply ADT selection", "Apply"),
    q("Data Structures", "For an undirected graph with edges A-B, B-C, C-D, starting at A, what is DFS order with alphabetical neighbors?",
      ["A, B, C, D", "A, C, B, D", "A, B, D, C", "A, D, C, B"], "A", "Apply DFS trace", "Apply"),
    q("Data Structures", "A BFS over a sparse graph is implemented with adjacency matrix and is slower than expected. Why?",
      ["Matrix representation causes O(V^2) neighbor scanning", "BFS cannot run on sparse graphs", "Queue operations are exponential", "Visited flags are unnecessary"], "A", "Analyze representation impact", "Analyze"),
    q("Data Structures", "Which algorithm is more suitable for finding shortest paths in weighted graphs with non-negative weights?",
      ["DFS", "BFS", "Dijkstra", "Topological sort"], "C", "Analyze algorithm suitability", "Analyze"),
    q("Data Structures", "Create a design for plagiarism detection requiring quick similarity lookup among many fingerprints.",
      ["Use inverted index plus hash-based candidate retrieval", "Use stack-only storage", "Sort files once and never update index", "Use random sampling only"], "A", "Create data-structure-based solution", "Create"),

    # Java / OOP (5)
    q("Java / OOP", "Why is interface-based design preferred in large Java systems?",
      ["It decouples clients from implementations and eases testing", "It prevents polymorphism", "It requires concrete class references everywhere", "It disables dependency injection"], "A", "Understand abstraction benefit", "Understand"),
    q("Java / OOP", "A method throws IOException. Which handling is valid in caller?",
      ["Catch IOException or declare throws IOException", "Ignore it because JVM handles all checked exceptions", "Catch only Error", "Replace with finally only"], "A", "Apply checked exception handling", "Apply"),
    q("Java / OOP", "What prints? String s=\"ab\"; s += \"cd\"; System.out.println(s.length());",
      ["2", "3", "4", "5"], "C", "Apply Java output trace", "Apply"),
    q("Java / OOP", "A subclass field hides a superclass field with same name. Access through superclass reference gives unexpected value. Why?",
      ["Field access is resolved by reference type, not runtime object type", "JVM forbids inheritance", "Method overloading controls field access", "Constructors are skipped"], "A", "Analyze Java binding rule", "Analyze"),
    q("Java / OOP", "Create a maintainable architecture for a Java admissions system integrating payment, notifications, and reporting.",
      ["Use layered architecture with service interfaces and dependency injection", "Put everything in one main class", "Use static global state for all modules", "Implement each feature as copy-paste package"], "A", "Create enterprise Java structure", "Create"),

    # Web Development (9)
    q("Web Development", "Why are semantic HTML tags (header, nav, main) recommended?",
      ["They improve accessibility and document structure meaning", "They reduce need for CSS files", "They replace backend APIs", "They encrypt content"], "A", "Understand semantic HTML", "Understand"),
    q("Web Development", "Why should CSRF tokens be used for state-changing requests in web apps?",
      ["They help verify the request came from the trusted user session context", "They compress payload size", "They replace authentication completely", "They prevent all XSS automatically"], "A", "Understand CSRF defense", "Understand"),
    q("Web Development", "A browser requests an API from another origin and receives blocked response. Which header is usually required?",
      ["Content-Type", "Access-Control-Allow-Origin", "Cache-Control", "User-Agent"], "B", "Apply CORS configuration", "Evaluate"),
    q("Web Development", "A page must cache static assets for one month but always fetch latest exam schedule JSON. Which approach fits?",
      ["Long cache for static files, no-cache/etag strategy for schedule endpoint", "Disable all caching globally", "Store schedule only in localStorage forever", "Use FTP refresh"], "A", "Apply caching policy", "Apply"),
    q("Web Development", "A REST API returns 409 on duplicate registration attempts. What does this indicate?",
      ["Conflict with current resource state", "Authentication success", "Server crash", "Permanent redirect"], "A", "Analyze HTTP status meaning", "Analyze"),
    q("Web Development", "Choose the best architecture for a school portal expecting seasonal traffic spikes and limited ops staff.",
      ["Stateless backend behind load balancer with managed database and autoscaling", "Single server with manual restart plan", "Browser-only app with no backend", "One process per student session"], "A", "Evaluate scalable web architecture", "Create"),
    q("Web Development", "Create URL and error-response standards for a public education API.",
      ["Consistent resource paths, versioning, and structured JSON errors", "Different format per endpoint", "Return plain text stack trace to users", "Hide all error codes"], "A", "Create API standards", "Create"),
    q("Web Development", "Design the best approach to protect uploaded assignment files from malware.",
      ["Virus-scan uploads asynchronously and quarantine suspicious files", "Trust file extension only", "Execute uploaded files to test safety", "Store files in public web root directly"], "A", "Create secure file handling flow", "Create"),
    q("Web Development", "Create a frontend performance plan for low-bandwidth users in regional campuses.",
      ["Code-split bundles, optimize images, lazy-load noncritical components", "Embed all media at full resolution", "Disable compression", "Load every script synchronously"], "A", "Create web optimization strategy", "Create"),

    # Android (5)
    q("Android", "Why should ViewModel be used with configuration changes like screen rotation?",
      ["It preserves UI-related state outside Activity recreation", "It replaces repositories", "It removes lifecycle awareness", "It stores data in manifest"], "A", "Understand ViewModel role", "Understand"),
    q("Android", "A feature must trigger local notification at 7:00 AM daily even after reboot. Which approach is appropriate?",
      ["Schedule with WorkManager/AlarmManager and reschedule on boot", "Run a busy loop in Activity", "Use Toast in onCreate only", "Depend on user opening app at 7:00"], "A", "Apply Android background scheduling", "Apply"),
    q("Android", "A team can collect precise location continuously for analytics or request coarse location only when feature is active. Which is the better privacy decision?",
      ["Request coarse/on-demand location with clear consent", "Track precise location all day by default", "Bypass permission prompts", "Store location forever without retention policy"], "A", "Evaluate privacy-conscious design", "Create"),
    q("Android", "Create an Android architecture for exam proctoring app with camera checks and intermittent connectivity.",
      ["Use modular features, local queue, and secure sync retries", "Upload only in real time and drop failures", "Keep camera stream in plain logs", "Use one singleton Activity"], "A", "Create robust app architecture", "Create"),
    q("Android", "Design the best release strategy for an app used by 200+ schools.",
      ["Staged rollout with crash monitoring and rollback readiness", "Release to all users at once without telemetry", "Skip QA after beta", "Disable update mechanism"], "A", "Create deployment strategy", "Create"),

    # Database (6)
    q("Database", "Why are foreign keys important in student-course enrollment tables?",
      ["They enforce referential integrity between related records", "They improve UI color themes", "They replace indexes", "They remove need for transactions"], "A", "Understand FK integrity", "Understand"),
    q("Database", "Given Employee(emp_id, dept_id, salary), which query returns each department's highest salary?",
      ["SELECT dept_id, MAX(salary) FROM Employee GROUP BY dept_id", "SELECT MAX(dept_id) FROM Employee", "SELECT salary FROM Employee WHERE MAX(salary)", "UPDATE Employee SET salary=MAX(salary)"], "A", "Apply aggregate SQL", "Apply"),
    q("Database", "In table ExamResult(student_id, course_id, grade), which SQL finds students who failed at least one course (grade < 50)?",
      ["SELECT DISTINCT student_id FROM ExamResult WHERE grade < 50", "SELECT student_id FROM ExamResult GROUP BY grade", "DELETE FROM ExamResult WHERE grade < 50", "SELECT * FROM ExamResult ORDER BY grade"], "A", "Apply filtering query", "Apply"),
    q("Database", "A relation stores advisor_name repeatedly for each student and advisor phone update needs many row changes. What issue is this?",
      ["Update anomaly due to redundancy", "Index fragmentation only", "Deadlock from two-phase locking", "Foreign key cascade"], "A", "Analyze normalization issue", "Analyze"),
    q("Database", "A team debates UUID primary keys everywhere vs numeric surrogate keys with unique business constraints. For high-write transactional tables, what is usually better default?",
      ["Numeric surrogate keys plus business unique constraints", "Random text keys without indexes", "No primary keys", "Composite keys with 10+ columns always"], "A", "Evaluate key strategy", "Evaluate"),
    q("Database", "Create a schema and retention model for security audit logs that must be queryable and tamper-evident.",
      ["Append-only audit table, partitioning, signed hash chain, retention policy", "Overwrite latest log row each day", "Store logs in client browser", "Disable timestamp fields"], "A", "Create secure data model", "Create"),

    # Operating Systems (6)
    q("Operating Systems", "Why does mutual exclusion matter when multiple threads update shared counters?",
      ["Without it, race conditions can produce incorrect values", "It makes threads run in parallel faster always", "It avoids deadlock by itself", "It removes need for atomic operations"], "A", "Understand critical-section control", "Understand"),
    q("Operating Systems", "A process has arrival 0 and burst 5; another arrival 1 burst 2. Under preemptive SJF (SRTF), which runs at time 1?",
      ["Process with remaining 4", "Process with burst 2", "Both simultaneously", "Idle"], "B", "Apply SRTF scheduling", "Apply"),
    q("Operating Systems", "A /26 subnet has 64 addresses. In OS network stack configuration, how many are typically usable for hosts?",
      ["62", "64", "60", "30"], "A", "Apply addressing in host config context", "Apply"),
    q("Operating Systems", "Four processes each hold one resource and request the next in a cycle. Which deadlock prevention action directly breaks this pattern?",
      ["Impose global resource ordering", "Increase CPU frequency", "Use shorter variable names", "Disable interrupts permanently"], "A", "Analyze deadlock prevention", "Analyze"),
    q("Operating Systems", "A machine spends most time swapping pages in/out and little time executing user code. What diagnosis fits?",
      ["Thrashing due to insufficient resident working set", "CPU starvation from priority inversion only", "Kernel panic", "Disk defragmentation"], "A", "Analyze paging behavior", "Analyze"),
    q("Operating Systems", "A lab can either run one huge process per student session or use process pool with controlled concurrency. Which is better?",
      ["Use process/thread pool with controlled concurrency", "Launch unbounded processes", "Disable scheduler timeslicing", "Use busy waiting for I/O"], "A", "Evaluate resource-management choice", "Evaluate"),

    # Software Engineering (16)
    q("Software Engineering", "Why should acceptance criteria be written per user story before implementation starts?",
      ["They align expectations and provide testable completion conditions", "They replace backlog prioritization", "They are only for auditors after release", "They prevent requirement changes forever"], "A", "Understand acceptance criteria", "Understand"),
    q("Software Engineering", "Why is backlog refinement important in agile projects?",
      ["It keeps work items clear, sized, and prioritized", "It removes sprint planning need", "It eliminates stakeholder feedback", "It prevents technical debt by definition"], "A", "Understand refinement purpose", "Understand"),
    q("Software Engineering", "Why is root-cause analysis done after repeated production incidents?",
      ["To identify systemic causes and prevent recurrence", "To assign blame quickly", "To avoid creating action items", "To increase ticket volume"], "A", "Understand RCA goal", "Understand"),
    q("Software Engineering", "Why should architecture decisions be documented as ADRs?",
      ["They capture context, options, and consequences for future teams", "They replace all code comments", "They are required only for AI projects", "They prevent refactoring"], "A", "Understand ADR value", "Understand"),
    q("Software Engineering", "A requirement says, 'Portal uptime must be 99.5% monthly.' This is an example of:",
      ["Functional requirement", "Non-functional reliability requirement", "User story estimate", "Implementation detail"], "B", "Apply requirement classification", "Apply"),
    q("Software Engineering", "A release introduces bug in payment feature. Which metric best reflects customer-facing quality impact?",
      ["Defect escape rate", "Lines of code changed", "Number of standups", "Repository size"], "A", "Apply quality metric selection", "Apply"),
    q("Software Engineering", "A team closes many tickets but lead time keeps increasing and rework grows. What is likely happening?",
      ["Work-in-progress is too high causing flow inefficiency", "Automation coverage is too high", "Requirements are too stable", "Team has too few meetings"], "A", "Analyze delivery flow symptom", "Analyze"),
    q("Software Engineering", "A project can meet deadline by skipping penetration testing or by reducing low-value analytics scope. Which choice is better?",
      ["Reduce low-value scope and keep security testing", "Skip security testing", "Delay all bug fixes", "Freeze stakeholder communication"], "A", "Evaluate release decision", "Affective"),
    q("Software Engineering", "Create a release readiness checklist for a government-facing education service.",
      ["Security scan, test pass, rollback plan, data migration check, approvals", "Only ensure app starts once", "Release when one developer says done", "Skip backup verification"], "A", "Create release governance artifact", "Create"),
    q("Software Engineering", "Create a dependency-management policy for third-party libraries.",
      ["Track versions, vulnerability scans, update cadence, and approval gates", "Install latest packages directly in production", "Ignore CVE reports", "Use unpinned transitive dependencies blindly"], "A", "Create supply-chain control", "Create"),
    q("Software Engineering", "Create a practical onboarding plan for new graduate developers joining the team.",
      ["Structured ramp-up with mentor, starter tasks, coding standards, and feedback checkpoints", "Assign critical production ownership on day one", "No documentation access", "Skip code review for newcomers"], "A", "Create people/process plan", "Create"),
    q("Software Engineering", "Create a rollback strategy for schema changes during high-stakes exam season.",
      ["Use backward-compatible migrations, backups, and tested rollback scripts", "Apply destructive migration directly in production", "Disable transactions for speed", "Drop old columns before app update"], "A", "Create safe deployment plan", "Create"),
    q("Software Engineering", "Design a cross-team incident communication protocol.",
      ["Define severity levels, single incident commander, update cadence, and postmortem", "Allow everyone to post conflicting updates", "Hide outages until resolved", "Use private messages only"], "A", "Create incident process", "Create"),
    q("Software Engineering", "Create a quality gate for merge requests in CI.",
      ["Require passing tests, lint checks, and code review approval", "Allow direct merges during busy weeks", "Run checks monthly only", "Ignore flaky tests permanently"], "A", "Create CI quality policy", "Create"),
    q("Software Engineering", "A stakeholder asks to hide a known fairness issue in automated scholarship ranking. What is the best professional response?",
      ["Refuse concealment, escalate concern, and address fairness transparently", "Comply silently to avoid conflict", "Delete evidence from reports", "Disable audit logs"], "A", "Ethical responsibility in software decisions", "Affective"),
    q("Software Engineering", "A teammate from another region struggles with communication due to language nuance. What behavior best supports collaboration?",
      ["Use clear written summaries, confirm understanding, and invite questions", "Avoid including them in design discussions", "Assume misunderstanding is incompetence", "Force only verbal updates"], "A", "Inclusive teamwork behavior", "Affective"),

    # Software Architecture (5)
    q("Software Architecture", "Why is explicit API contract versioning useful in distributed systems?",
      ["It enables backward compatibility and controlled evolution", "It removes need for testing", "It prevents deployment automation", "It replaces authentication"], "A", "Understand API evolution", "Understand"),
    q("Software Architecture", "An exam platform needs strict consistency for scores and eventual consistency for analytics. Which architecture decision is best?",
      ["Use transactional core services and asynchronous analytics pipeline", "Use eventual consistency for score submission and ranking", "Store all data in browser cache", "Avoid message queues"], "A", "Evaluate consistency trade-off", "Evaluate"),
    q("Software Architecture", "Create a microservices decomposition for digital library platform.",
      ["Catalog, Borrowing, Identity, Recommendation, and Notification services", "Single service with shared mutable globals", "Service per database table", "No service boundaries"], "A", "Create service boundaries", "Create"),
    q("Software Architecture", "Design architecture for multi-tenant schools with isolated data and shared operations.",
      ["Tenant-aware service layer with row-level isolation and per-tenant controls", "One shared admin account and shared schema without tenant keys", "Separate codebase per student", "Local file storage only"], "A", "Create multi-tenant architecture", "Create"),
    q("Software Architecture", "Create resilience strategy for downstream payment outages.",
      ["Circuit breakers, retries with backoff, idempotency keys, and fallback queue", "Infinite tight-loop retries", "Synchronous blocking calls everywhere", "Manual restart as only control"], "A", "Create fault-tolerant architecture", "Create"),

    # Project Management (5)
    q("Project Management", "Why are stakeholder influence and interest mapped at project start?",
      ["To tailor communication and decision engagement plans", "To avoid documenting requirements", "To replace schedule baselines", "To estimate CPU usage"], "A", "Understand stakeholder mapping", "Understand"),
    q("Project Management", "A project has tasks: A(3d) then B(2d) and C(4d) in parallel, then D(2d) after both. What is total duration?",
      ["7 days", "8 days", "9 days", "11 days"], "C", "Apply simple CPM", "Apply"),
    q("Project Management", "A sponsor requests a major scope addition mid-sprint with fixed deadline. What is the best PM response?",
      ["Assess impact and negotiate scope/time/cost trade-off formally", "Accept immediately and hide risk", "Cut testing silently", "Ignore sponsor request"], "A", "Evaluate change-control response", "Create"),
    q("Project Management", "Create a communication plan for a project spanning universities in multiple time zones.",
      ["Define cadence, channels, escalation paths, and artifact owners", "Hold ad-hoc meetings only", "Send updates only at project end", "Avoid written records"], "A", "Create PM communication framework", "Create"),
    q("Project Management", "Create the best sprint planning structure for teams with mixed seniority.",
      ["Set sprint goal, estimate collaboratively, identify risks, and pair juniors with mentors", "Assign tasks unilaterally without discussion", "Skip retrospectives always", "Plan by intuition only"], "A", "Create team-aware planning process", "Create"),

    # Software Testing (5)
    q("Software Testing", "Why is test data management important in integration testing?",
      ["Realistic and controlled data improves defect detection reliability", "Any random data is always sufficient", "It only affects UI color testing", "It replaces environment setup"], "A", "Understand data strategy in testing", "Understand"),
    q("Software Testing", "A login allows 5 attempts before lockout. Which test is most relevant?",
      ["Attempt 5 success then 6th fails/locks", "Only valid username once", "Check homepage title", "Delete user table"], "A", "Apply security test case design", "Analyze"),
    q("Software Testing", "Production issue occurs only when two services update same record concurrently. Which missing test type is indicated?",
      ["Concurrency/integration scenario testing", "Spelling test", "Screenshot testing only", "Static code formatting"], "A", "Analyze missing coverage", "Evaluate"),
    q("Software Testing", "Create a regression selection strategy for daily CI runs.",
      ["Run risk-based core suite daily and full suite nightly", "Run full manual suite after each commit", "Skip regression unless users complain", "Run only newly written tests"], "A", "Create scalable test strategy", "Create"),
    q("Software Testing", "Create a quality dashboard for release decision meetings.",
      ["Track pass rate, defect severity trend, escaped defects, and coverage", "Count only test cases written", "Use build duration only", "Display random KPI each week"], "A", "Create decision-support QA metrics", "Create"),

    # Networking (6)
    q("Networking", "Why is CIDR used instead of old classful addressing?",
      ["It allows flexible allocation and efficient route aggregation", "It disables subnetting", "It guarantees no routing loops", "It removes need for gateways"], "A", "Understand CIDR purpose", "Understand"),
    q("Networking", "A /24 network is split into 4 equal subnets. What is each new prefix?",
      ["/25", "/26", "/27", "/28"], "B", "Apply subnet split math", "Apply"),
    q("Networking", "A /26 subnet has how many usable host addresses?",
      ["62", "64", "30", "126"], "A", "Apply host-count formula", "Apply"),
    q("Networking", "Traffic captures show repeated ARP replies mapping gateway IP to attacker MAC. What is this?",
      ["ARP spoofing/poisoning", "DNS amplification", "BGP hijack", "Port mirroring"], "A", "Analyze LAN attack behavior", "Remember"),
    q("Networking", "Create a campus network design that isolates lab, admin, and guest traffic while allowing controlled access.",
      ["Use VLAN segmentation, inter-VLAN firewall rules, and NAC", "Use one flat subnet for all users", "Disable ACLs to simplify routing", "Allow guest access to admin DB"], "A", "Create segmented network architecture", "Create"),
    q("Networking", "A regional office can choose static routes everywhere or dynamic routing with OSPF for expanding branches. Which is better?",
      ["Dynamic routing with OSPF for scalability and resilience", "Static routes only forever", "No routing protocol plus NAT only", "Use hubs to avoid L3"], "A", "Evaluate routing strategy", "Evaluate"),

    # Security (5)
    q("Security", "Why is principle of least privilege central to secure system design?",
      ["It limits damage if an account is compromised", "It grants faster admin access to all users", "It removes need for authentication", "It requires shared root accounts"], "A", "Understand least privilege", "Understand"),
    q("Security", "A web app stores session ID in URL and logs it in proxies. Which secure fix is best?",
      ["Use secure HttpOnly cookies and rotate session IDs", "Keep URL session and hide logs", "Disable logout endpoints", "Store passwords in cookies"], "A", "Apply session security controls", "Apply"),
    q("Security", "A server certificate expires during exam week. Which immediate action is best?",
      ["Renew certificate and automate renewal monitoring", "Switch to HTTP temporarily", "Ignore warning dialogs", "Disable browser certificate checks"], "A", "Apply operational security practice", "Apply"),
    q("Security", "A municipality must choose between SMS OTP only and phishing-resistant MFA using authenticator app or FIDO key for admin accounts. Which is best?",
      ["Phishing-resistant MFA for admin accounts", "SMS OTP only for all high-risk accounts", "No MFA for internal users", "Shared password vault login"], "A", "Evaluate MFA strength", "Affective"),
    q("Security", "A penetration tester discovers exposed student data API in staging. What team behavior is most appropriate?",
      ["Coordinate responsible disclosure, fix quickly, and share lessons learned", "Publish exploit publicly before notifying team", "Ignore because environment is staging", "Delete test report"], "A", "Security-minded professional conduct", "Affective"),

    # AI / ML (10)
    q("AI / ML", "Why is cross-validation useful when dataset size is limited?",
      ["It estimates model generalization more reliably across folds", "It guarantees best hyperparameters always", "It removes need for holdout data", "It works only for deep learning"], "A", "Understand cross-validation", "Understand"),
    q("AI / ML", "Why should fairness metrics be monitored for scholarship ranking models?",
      ["Model performance can differ across demographic groups", "Fairness checks reduce all accuracy to zero", "Fairness is only legal issue, not technical", "Bias disappears after normalization"], "A", "Understand fairness monitoring", "Understand"),
    q("AI / ML", "A binary classifier has TP=90, FP=30, FN=10, TN=70. What is recall?",
      ["0.75", "0.80", "0.90", "0.97"], "C", "Apply recall formula", "Apply"),
    q("AI / ML", "For multiclass image classification, which evaluation summary handles class imbalance better than plain accuracy?",
      ["Macro-averaged F1 score", "Training loss after first epoch", "Model file size", "GPU temperature"], "A", "Apply metric choice", "Apply"),
    q("AI / ML", "A model's training loss decreases steadily but validation loss increases after epoch 12. What does this indicate?",
      ["Overfitting after epoch 12", "Underfitting improving", "Data leakage resolved", "Optimizer failure to update"], "A", "Analyze learning curves", "Analyze"),
    q("AI / ML", "Create a human-in-the-loop review workflow for high-stakes automated decisions.",
      ["Route low-confidence cases to human reviewers with rationale logs", "Auto-approve all low-confidence outputs", "Hide confidence scores from operators", "Disable audit trail"], "A", "Create governance-aware AI workflow", "Create"),
    q("AI / ML", "Create a deployment architecture for low-latency speech scoring in exam centers with unstable connectivity.",
      ["Edge inference with periodic cloud sync and fallback queue", "Cloud-only inference with no retry", "Manual scoring from raw waveform dumps", "Single-threaded batch mode only"], "A", "Create edge-cloud AI design", "Create"),
    q("AI / ML", "Create a data labeling quality plan for large Amharic text corpus.",
      ["Guidelines, overlap labeling, adjudication, and inter-annotator agreement tracking", "One annotator with no review", "Accept labels without consistency checks", "Skip documentation"], "A", "Create labeling QA process", "Create"),
    q("AI / ML", "Design the best monitoring set for a production recommendation model.",
      ["Latency, error rate, drift metrics, CTR, and fairness slices", "Only model file timestamp", "GPU fan speed only", "Random KPI rotation"], "A", "Create comprehensive model monitoring", "Create"),
    q("AI / ML", "Create an experimentation protocol for comparing two ranking models online safely.",
      ["Use A/B test with guardrail metrics and rollback criteria", "Deploy both globally without measurement", "Pick model by intuition", "Run experiment without ethics review"], "A", "Create controlled experimentation plan", "Create"),
]
# fmt: on


validate_bank(BANK_V2, TOPIC_COUNTS_V2)
validate_bank(BANK_V3, TOPIC_COUNTS_V3)
