"""Predicted 2018 Software Engineering exit exam — 100 MCQs."""

from __future__ import annotations


def _q(topic: str, text: str, opts: list[str], answer: str, concept: str) -> dict:
    keys = "ABCD"
    return {
        "topic": topic,
        "text": text,
        "options": [{"key": k, "text": t} for k, t in zip(keys, opts)],
        "answer": answer,
        "concept": f"Key idea ({topic}): {concept}",
    }


# fmt: off
PREDICTED_2018_QUESTIONS: list[dict] = [
    # Fundamentals of Programming (5)
    _q("Fundamentals of Programming", "Which of the following is a valid C++ identifier?",
       ["2variable", "variable-2", "_count123", "class"], "C", "Valid identifiers start with letter or underscore"),
    _q("Fundamentals of Programming", "What is the primary purpose of a breakpoint in debugging?",
       ["To mark the start of a loop", "To pause program execution at a chosen line", "To end a function", "To indicate a syntax error"], "B", "Breakpoint pauses execution for inspection"),
    _q("Fundamentals of Programming", "Which programming paradigm focuses on step-by-step instructions and mutable state?",
       ["Object-oriented", "Procedural", "Declarative", "Logic"], "B", "Procedural paradigm"),
    _q("Fundamentals of Programming", "A compiler differs from an interpreter because a compiler:",
       ["Executes code line by line at runtime", "Translates the entire program before execution", "Only checks syntax without producing output", "Runs only on web browsers"], "B", "Compiler translates whole program first"),
    _q("Fundamentals of Programming", "Which type of error is detected by the compiler before the program runs?",
       ["Runtime error", "Logic error", "Syntax error", "Semantic error in business rules"], "C", "Syntax errors caught at compile time"),

    # C++ (4)
    _q("C++", "What is the output of: for(int i=0; i<3; i++) cout << i;",
       ["012", "123", "0123", "001"], "A", "Loop prints 0, 1, 2"),
    _q("C++", "Which of the following is NOT a valid C++ variable name?",
       ["variable_1234", "myVar", "64bit", "totalScore"], "C", "Identifiers cannot start with a digit"),
    _q("C++", "In C++, which operator is used for dynamic memory allocation?",
       ["malloc", "new", "alloc", "create"], "B", "new operator in C++"),
    _q("C++", "Which header file is typically required for cout in C++?",
       ["<stdio.h>", "<iostream>", "<conio.h>", "<string.h>"], "B", "iostream for cout"),

    # Data Structures (6)
    _q("Data Structures", "Which data structure uses LIFO (Last In, First Out) ordering?",
       ["Queue", "Stack", "Binary tree", "Graph"], "B", "Stack is LIFO"),
    _q("Data Structures", "What is the average time complexity of lookup in a hash table?",
       ["O(1)", "O(log n)", "O(n)", "O(n log n)"], "A", "Hash table average O(1) lookup"),
    _q("Data Structures", "Suppose you need efficient insertion and deletion with fast average lookup. Which structure fits best?",
       ["Stack", "Queue", "Hash table", "Sorted array only"], "C", "Hash table for insert/delete/lookup"),
    _q("Data Structures", "Breadth-First Search (BFS) on a graph typically uses which auxiliary structure?",
       ["Stack", "Queue", "Priority queue only", "Hash set only"], "B", "BFS uses a queue"),
    _q("Data Structures", "What is the time complexity of binary search on a sorted array of n elements?",
       ["O(1)", "O(log n)", "O(n)", "O(n²)"], "B", "Binary search O(log n)"),
    _q("Data Structures", "Which sorting algorithm has worst-case O(n²) but is simple to implement?",
       ["Merge sort", "Quick sort (worst case)", "Bubble sort", "Heap sort"], "C", "Bubble sort O(n²)"),

    # Java / OOP (6)
    _q("Java / OOP", "Which OOP principle hides internal object state and exposes controlled access?",
       ["Inheritance", "Encapsulation", "Polymorphism", "Abstraction only in interfaces"], "B", "Encapsulation hides state"),
    _q("Java / OOP", "In Java, a class that provides a partial implementation and cannot be instantiated directly is:",
       ["Interface", "Abstract class", "Final class", "Static class"], "B", "Abstract class"),
    _q("Java / OOP", "Which keyword in Java prevents a method from being overridden in a subclass?",
       ["static", "final", "abstract", "private"], "B", "final methods cannot be overridden"),
    _q("Java / OOP", "Polymorphism allows:",
       ["One name, many forms — same interface, different behavior", "Only single inheritance", "No method overriding", "Only compile-time binding"], "A", "Polymorphism — one interface many forms"),
    _q("Java / OOP", "How many times is the catch block executed when multiple exceptions could occur in one try?",
       ["Once for each exception", "Once regardless of how many exceptions occur", "Never if finally exists", "Only for checked exceptions"], "B", "Single catch execution per try"),
    _q("Java / OOP", "Which statement about Java interfaces is TRUE?",
       ["A class can implement multiple interfaces", "A class can extend multiple classes", "Interfaces can be instantiated directly", "All interface methods must have bodies in Java 8+"], "A", "Multiple interface implementation"),

    # Web Development (7)
    _q("Web Development", "Which HTTP method is most appropriate for submitting login credentials?",
       ["GET", "POST", "HEAD", "DELETE"], "B", "POST for form/credential submission"),
    _q("Web Development", "What does HTTP status code 404 indicate?",
       ["Server error", "Resource not found", "Successful creation", "Redirect"], "B", "404 Not Found"),
    _q("Web Development", "Which technology adds interactivity and dynamic behavior to web pages in the browser?",
       ["HTML only", "CSS only", "JavaScript", "FTP"], "C", "JavaScript for interactivity"),
    _q("Web Development", "AJAX allows a web page to:",
       ["Reload entirely for every user action", "Update parts of a page asynchronously without full reload", "Replace HTML with CSS", "Disable HTTP"], "B", "AJAX asynchronous partial updates"),
    _q("Web Development", "In CSS, which selector targets an element with id=\"header\"?",
       [".header", "#header", "header:", "element.header"], "B", "# for id selector"),
    _q("Web Development", "HTTPS differs from HTTP primarily because HTTPS:",
       ["Uses port 21", "Encrypts communication with TLS/SSL", "Is stateful by default", "Only supports GET"], "B", "HTTPS adds TLS encryption"),
    _q("Web Development", "Which HTML tag defines the largest heading level?",
       ["<h6>", "<h1>", "<head>", "<header>"], "B", "h1 is largest heading"),

    # Android (5)
    _q("Android", "Which Android component handles a single screen with a user interface?",
       ["Service", "Activity", "Broadcast Receiver", "Content Provider"], "B", "Activity = screen UI"),
    _q("Android", "What is an Intent used for in Android?",
       ["To encrypt APK files", "To request an action from another component", "To compile Java to Dalvik", "To define CSS layouts"], "B", "Intent requests actions"),
    _q("Android", "Which file declares app components, permissions, and package name?",
       ["build.gradle", "AndroidManifest.xml", "activity_main.xml", "R.java"], "B", "AndroidManifest.xml"),
    _q("Android", "APK stands for:",
       ["Android Package Kit", "Application Process Kernel", "Automated Program Key", "Android Protocol Knowledge"], "A", "Android Package Kit"),
    _q("Android", "Which class is the base for all UI layout containers in Android?",
       ["View", "ViewGroup", "Fragment only", "Service"], "B", "ViewGroup for layouts"),

    # Database (6)
    _q("Database", "Which normal form eliminates partial dependency on a composite primary key?",
       ["1NF", "2NF", "3NF", "BCNF only"], "B", "2NF removes partial dependencies"),
    _q("Database", "Which SQL clause filters rows after grouping?",
       ["WHERE", "HAVING", "ORDER BY", "GROUP BY"], "B", "HAVING filters groups"),
    _q("Database", "A primary key must be:",
       ["Nullable and duplicate", "Unique and not null", "Only composite", "Always an integer"], "B", "Primary key unique and NOT NULL"),
    _q("Database", "Which property of ACID ensures all operations complete or none do?",
       ["Atomicity", "Consistency", "Isolation", "Durability"], "A", "Atomicity all-or-nothing"),
    _q("Database", "Which SQL statement retrieves all columns from table Students?",
       ["GET * FROM Students", "SELECT ALL Students", "SELECT * FROM Students", "FETCH Students"], "C", "SELECT * FROM Students"),
    _q("Database", "In ER modeling, a relationship between Student and Course typically represents:",
       ["A weak entity only", "Enrollment or association between entities", "A derived attribute", "A surrogate key only"], "B", "Relationship models association"),

    # Operating Systems (6)
    _q("Operating Systems", "Which process state means the process is ready to run but waiting for the CPU?",
       ["Running", "Ready", "Blocked", "Terminated"], "B", "Ready state waits for CPU"),
    _q("Operating Systems", "Which condition for deadlock means a resource can be held by only one process at a time?",
       ["Hold and wait", "Mutual exclusion", "Circular wait", "No preemption"], "B", "Mutual exclusion"),
    _q("Operating Systems", "Which page replacement algorithm may suffer from Belady's anomaly?",
       ["FIFO", "LRU", "Optimal", "LFU"], "A", "FIFO Belady anomaly"),
    _q("Operating Systems", "Virtual memory primarily allows:",
       ["Faster CPU clock speed", "Programs larger than physical RAM to run", "Elimination of all I/O", "Single-user systems only"], "B", "Virtual memory extends address space"),
    _q("Operating Systems", "Which scheduling algorithm can cause starvation for low-priority processes?",
       ["FCFS", "Round Robin", "Priority scheduling", "First-fit memory allocation"], "C", "Priority scheduling starvation"),
    _q("Operating Systems", "A deadlock can be prevented by breaking which condition?",
       ["Any one of the four necessary conditions", "Only mutual exclusion always", "Only circular wait never", "Hold and wait cannot be broken"], "A", "Break any deadlock condition"),

    # Software Engineering (16)
    _q("Software Engineering", "Which SDLC model delivers working software in short iterative cycles with frequent feedback?",
       ["Waterfall", "Agile", "Big Bang", "Code-and-fix only"], "B", "Agile iterative delivery"),
    _q("Software Engineering", "Requirements that describe system qualities like performance and security are:",
       ["Functional requirements", "Non-functional requirements", "Use cases only", "Design patterns"], "B", "Non-functional requirements"),
    _q("Software Engineering", "Which maintenance type fixes faults discovered after deployment?",
       ["Adaptive", "Perfective", "Corrective", "Preventive only"], "C", "Corrective maintenance"),
    _q("Software Engineering", "A code smell indicates:",
       ["Syntax error caught by compiler", "A surface symptom of deeper design problem", "Successful refactoring", "Completed unit test"], "B", "Code smell signals design issue"),
    _q("Software Engineering", "Refactoring means changing code structure without:",
       ["Changing external behavior", "Using version control", "Writing tests", "Reading requirements"], "A", "Refactoring preserves behavior"),
    _q("Software Engineering", "Which SRS quality means requirements can be verified by test or analysis?",
       ["Ambiguous", "Testable", "Incomplete", "Inconsistent"], "B", "Testable requirement"),
    _q("Software Engineering", "The spiral model emphasizes:",
       ["No risk analysis", "Risk-driven iterative development", "Single release only", "No prototyping"], "B", "Spiral model risk-driven"),
    _q("Software Engineering", "Which activity belongs to requirements elicitation?",
       ["Writing machine code", "Interviewing stakeholders to discover needs", "Deploying to production", "Replacing hardware"], "B", "Elicitation discovers needs"),
    _q("Software Engineering", "Change control in requirements management ensures:",
       ["All changes are ignored", "Changes are evaluated, approved, and tracked", "Only developers change scope freely", "Testing is skipped"], "B", "Controlled change management"),
    _q("Software Engineering", "Technical debt refers to:",
       ["Money owed to cloud providers", "Future cost of expedient shortcuts in design/code", "Hardware loan agreements", "Open-source licensing fees"], "B", "Technical debt future rework cost"),
    _q("Software Engineering", "Which document describes WHAT the system should do from the user's perspective?",
       ["Source code", "Requirements specification", "Machine binary", "Network topology diagram"], "B", "Requirements specify what"),
    _q("Software Engineering", "Preventive maintenance aims to:",
       ["Fix user-reported bugs only", "Prevent future problems through proactive changes", "Add unrelated features", "Remove all documentation"], "B", "Preventive maintenance proactive"),
    _q("Software Engineering", "Coupling measures:",
       ["How strongly modules depend on each other", "Lines of code only", "CPU utilization", "Screen resolution"], "A", "Coupling inter-module dependency"),
    _q("Software Engineering", "Cohesion measures:",
       ["Degree to which elements within a module belong together", "Network bandwidth", "Number of programmers", "Database size"], "A", "Cohesion intra-module unity"),
    _q("Software Engineering", "Which is a functional requirement example?",
       ["System shall respond within 2 seconds", "System shall allow users to reset password", "System shall use AES-256", "System shall run on Linux"], "B", "Password reset is functional"),
    _q("Software Engineering", "Software reengineering differs from replacement because reengineering:",
       ["Starts from scratch always", "Improves existing system while preserving essential behavior", "Eliminates all testing", "Removes all users"], "B", "Reengineering improves existing system"),

    # Software Architecture (5)
    _q("Software Architecture", "Which architectural style splits a system into independent deployable services?",
       ["Monolithic", "Microservices", "Single-tier only", "Flat file system"], "B", "Microservices architecture"),
    _q("Software Architecture", "An API gateway in microservices primarily:",
       ["Stores all database records", "Routes and aggregates client requests to backend services", "Replaces the OS kernel", "Compiles Java source"], "B", "API gateway routes requests"),
    _q("Software Architecture", "Which quality attribute measures ability to handle increased load?",
       ["Scalability", "Portability only", "Usability only", "Localization"], "A", "Scalability under load"),
    _q("Software Architecture", "Layered architecture organizes the system into:",
       ["Random modules", "Hierarchical layers with defined dependencies", "No interfaces", "Only hardware layers"], "B", "Layered hierarchical structure"),
    _q("Software Architecture", "The Singleton design pattern ensures:",
       ["Many instances of a class", "Exactly one instance of a class", "No constructors", "Only static methods forbidden"], "B", "Singleton one instance"),

    # Project Management (6)
    _q("Project Management", "Work Breakdown Structure (WBS) is used to:",
       ["Decompose project work into manageable components", "Replace all testing", "Encrypt project files", "Define network protocols"], "A", "WBS decomposes work"),
    _q("Project Management", "Critical Path Method (CPM) identifies:",
       ["Longest sequence of dependent tasks determining minimum project duration", "Shortest unrelated tasks", "Only optional tasks", "Hardware failures"], "A", "Critical path minimum duration"),
    _q("Project Management", "In agile, which value is preferred over following a fixed plan?",
       ["Processes over people", "Responding to change", "Contract negotiation over collaboration", "Documentation over software"], "B", "Agile values responding to change"),
    _q("Project Management", "Resource leveling in project scheduling aims to:",
       ["Eliminate all resources", "Resolve over-allocation by adjusting task timing", "Skip the critical path", "Remove the WBS"], "B", "Resource leveling resolves over-allocation"),
    _q("Project Management", "ROI (Return on Investment) measures:",
       ["Network latency", "Financial gain relative to cost", "Lines of code", "Number of meetings"], "B", "ROI financial return vs cost"),
    _q("Project Management", "Tuckman's team development stages include:",
       ["Design, code, test, deploy only", "Forming, storming, norming, performing", "Compile, link, run only", "TCP, UDP, IP only"], "B", "Tuckman team stages"),

    # Software Testing (5)
    _q("Software Testing", "Which test level verifies interactions between integrated modules?",
       ["Unit testing", "Integration testing", "Acceptance testing only", "Hardware testing"], "B", "Integration testing module interactions"),
    _q("Software Testing", "Black-box testing focuses on:",
       ["Internal code structure only", "Inputs and expected outputs without knowing implementation", "Compiler internals", "CPU registers only"], "B", "Black-box I/O behavior"),
    _q("Software Testing", "Equivalence partitioning divides:",
       ["Project budget", "Input domain into classes expected to behave similarly", "Network cables", "Team members"], "B", "Equivalence partitioning input classes"),
    _q("Software Testing", "Verification asks: 'Are we building the product right?' Validation asks:",
       ["Are we building the right product?", "Are we using Java?", "Is the network fast?", "Is HTML valid?"], "A", "Validation — right product"),
    _q("Software Testing", "Regression testing ensures:",
       ["Old bugs never fixed", "New changes have not broken existing functionality", "Only new features work once", "Users never test"], "B", "Regression detects new breakage"),

    # Networking (7)
    _q("Networking", "Which OSI layer handles routing and logical addressing?",
       ["Physical", "Data Link", "Network", "Application"], "C", "Network layer routing"),
    _q("Networking", "A switch operates primarily at which OSI layer?",
       ["Layer 1 only", "Layer 2 (Data Link)", "Layer 7 only", "Layer 5 only"], "B", "Switch at Layer 2"),
    _q("Networking", "Which topology provides the highest redundancy through multiple paths?",
       ["Bus", "Star", "Mesh", "Linear"], "C", "Mesh high redundancy"),
    _q("Networking", "TCP is connection-oriented and reliable; UDP is:",
       ["Connectionless and best-effort", "Always encrypted", "Used only for email", "Layer 1 protocol"], "A", "UDP connectionless best-effort"),
    _q("Networking", "The three-way handshake (SYN, SYN-ACK, ACK) establishes:",
       ["DNS resolution", "TCP connection", "UDP session", "HTTP cookie"], "B", "TCP three-way handshake"),
    _q("Networking", "DNS primarily translates:",
       ["MAC addresses to IP", "Domain names to IP addresses", "IP to port numbers", "HTML to CSS"], "B", "DNS name to IP"),
    _q("Networking", "Which device connects different networks and uses IP addresses for forwarding?",
       ["Hub", "Repeater", "Router", "Bridge only within same network"], "C", "Router connects networks"),

    # Security (7)
    _q("Security", "The CIA triad stands for Confidentiality, Integrity, and:",
       ["Availability", "Authentication only", "Anonymity", "Accounting"], "A", "CIA — Availability"),
    _q("Security", "Which encryption algorithm is commonly used to secure data at rest in databases?",
       ["AES", "ICMP", "ARP", "HTTP"], "A", "AES for data at rest"),
    _q("Security", "Cross-Site Scripting (XSS) allows an attacker to:",
       ["Inject malicious scripts into web pages viewed by others", "Physically steal servers", "Replace CPU firmware only", "Disable DNS permanently"], "A", "XSS injects scripts"),
    _q("Security", "A firewall primarily:",
       ["Compiles source code", "Filters network traffic based on rules", "Formats hard drives", "Runs unit tests"], "B", "Firewall filters traffic"),
    _q("Security", "Multi-Factor Authentication (MFA) requires:",
       ["Only one factor", "Two or more independent verification factors", "No passwords ever", "Only biometric data"], "B", "MFA multiple factors"),
    _q("Security", "Malware that encrypts files and demands payment is typically:",
       ["Ransomware", "Adware only", "Browser cache", "Open-source license"], "A", "Ransomware encryption extortion"),
    _q("Security", "Hashing (e.g., SHA-256) is primarily used for:",
       ["Reversible encryption of bulk data", "Integrity verification — detecting tampering", "Routing packets", "DNS lookup"], "B", "Hashing for integrity"),

    # AI / ML (9)
    _q("AI / ML", "Which type of machine learning uses labeled training data?",
       ["Unsupervised learning", "Supervised learning", "Clustering only", "Expert system inference only"], "B", "Supervised learning labeled data"),
    _q("AI / ML", "A* search is considered informed because it uses:",
       ["Random choices only", "A heuristic estimate toward the goal", "No cost function", "Only depth-first expansion"], "B", "A* uses heuristic"),
    _q("AI / ML", "K-means is an example of:",
       ["Supervised classification", "Unsupervised clustering", "Reinforcement learning", "Logic programming"], "B", "K-means clustering"),
    _q("AI / ML", "Which search strategy explores the shallowest nodes first?",
       ["DFS", "BFS", "Greedy best-first only", "Hill climbing only"], "B", "BFS shallowest first"),
    _q("AI / ML", "An intelligent agent perceives its environment through:",
       ["Sensors and acts through actuators", "Only human operators", "Compilers", "CSS selectors"], "A", "Agent sensors and actuators"),
    _q("AI / ML", "Decision trees are commonly used for:",
       ["Classification and regression", "Network routing only", "Memory paging", "HTML parsing only"], "A", "Decision trees classification/regression"),
    _q("AI / ML", "Overfitting occurs when a model:",
       ["Performs well on training data but poorly on new data", "Never learns training data", "Has no parameters", "Uses no training data"], "A", "Overfitting poor generalization"),
    _q("AI / ML", "Expert systems often represent knowledge using:",
       ["If-then rules", "Only binary images", "TCP headers", "SQL joins only"], "A", "Expert systems rule bases"),
    _q("AI / ML", "Uniform Cost Search expands nodes in order of:",
       ["Heuristic estimate only", "Path cost from the start", "Random order", "Alphabetical node names"], "B", "UCS by path cost"),
]
# fmt: on

TOPIC_COUNTS = {
    "Fundamentals of Programming": 5,
    "C++": 4,
    "Data Structures": 6,
    "Java / OOP": 6,
    "Web Development": 7,
    "Android": 5,
    "Database": 6,
    "Operating Systems": 6,
    "Software Engineering": 16,
    "Software Architecture": 5,
    "Project Management": 6,
    "Software Testing": 5,
    "Networking": 7,
    "Security": 7,
    "AI / ML": 9,
}

assert len(PREDICTED_2018_QUESTIONS) == 100, len(PREDICTED_2018_QUESTIONS)
from collections import Counter
_actual = Counter(q["topic"] for q in PREDICTED_2018_QUESTIONS)
for topic, count in TOPIC_COUNTS.items():
    assert _actual[topic] == count, f"{topic}: expected {count}, got {_actual[topic]}"

FOCUS_GUIDE = {
    "Fundamentals of Programming": "Loops, operators, debugging, paradigms, and basic programming concepts.",
    "C++": "Syntax, loops, identifiers, headers, and memory operators.",
    "Data Structures": "Stacks, queues, trees, graphs, BFS/DFS, hash tables, and Big-O reasoning.",
    "Java / OOP": "Inheritance, interfaces, encapsulation, polymorphism, and Java keywords.",
    "Web Development": "HTML/CSS/JS, HTTP methods, status codes, AJAX, and HTTPS.",
    "Android": "Activity, Intent, Manifest, ViewGroup, and APK components.",
    "Database": "Keys, normalization, SQL, ER mapping, and ACID properties.",
    "Operating Systems": "Process states, deadlock, scheduling, paging, and virtual memory.",
    "Software Engineering": "SDLC, requirements, refactoring, code smells, maintenance, and coupling.",
    "Software Architecture": "Microservices, API gateway, quality attributes, and design patterns.",
    "Project Management": "WBS, Gantt, critical path, agile values, and Tuckman stages.",
    "Software Testing": "Test levels, V&V, black/white box, equivalence partitioning, regression.",
    "Networking": "OSI layers, TCP/UDP, topologies, DNS, switches vs routers.",
    "Security": "CIA triad, AES, XSS, firewalls, MFA, malware, and hashing.",
    "AI / ML": "Supervised vs unsupervised, A*/BFS/UCS, agents, K-means, decision trees.",
}
