"""2025 MoEE Software Engineering Exit Exam — question bank."""

from __future__ import annotations

FOCUS_GUIDE: dict[str, str] = {
    "Fundamentals of Programming": "Loops, variables, operators, complexity, modular design, Python/Java/C basics.",
    "Data Structures": "Linked lists, stacks, queues, trees, sorting, graph algorithms, Big-O.",
    "Java / OOP": "Inheritance, encapsulation, polymorphism, this/super, method overriding.",
    "Web Development": "HTML, CSS, JavaScript, AJAX, HTTP methods, Django/frameworks.",
    "Android": "Activities, Intents, Manifest, Java/Kotlin, mobile security.",
    "Database": "Keys, SQL, normalization, relationships, ACID.",
    "Operating Systems": "Scheduling, deadlock, paging, mutex, security.",
    "Software Engineering": "SDLC models, Agile, UML, feasibility, NFRs.",
    "Software Architecture": "Architecture role, design patterns, quality attributes, UML structure.",
    "Project Management": "WBS, Gantt, risk, Scrum roles, scheduling.",
    "Software Testing": "Unit/white-box testing, test cases, QA goals, defects.",
    "Software Maintenance": "Maintenance types, refactoring, complexity cost, reliability.",
    "Networking": "OSI model, routing, HTTPS, subnet mask, gateways.",
    "Security": "Encryption, SQL injection, firewall, MFA, patching.",
    "AI / ML": "Agents, search, expert systems, supervised/unsupervised, overfitting.",
}

# Each entry: (text, [(A,text), (B,text), (C,text), (D,text)], answer, topic)
RAW: list[tuple] = [
    ("What is the primary purpose of a loop in programming?",
     [("A", "To declare variables"), ("B", "To execute a block of code repeatedly"),
      ("C", "To define a function"), ("D", "To handle exceptions")], "B", "Fundamentals of Programming"),
    ("In C, what is the output of the code: printf(\"%d\", 5 / 2);?",
     [("A", "2.5"), ("B", "2"), ("C", "3"), ("D", "0")], "B", "Fundamentals of Programming"),
    ("Which of the following is a valid variable name in Python?",
     [("A", "1variable"), ("B", "variable_1"), ("C", "variable-1"), ("D", "variable#1")], "B", "Fundamentals of Programming"),
    ("What does the break statement do in a loop?",
     [("A", "Skips the current iteration"), ("B", "Exits the loop entirely"),
      ("C", "Restarts the loop"), ("D", "Continues to the next iteration")], "B", "Fundamentals of Programming"),
    ("In Java, which keyword is used to define a constant?",
     [("A", "static"), ("B", "final"), ("C", "const"), ("D", "immutable")], "B", "Fundamentals of Programming"),
    ("What is the time complexity of a linear search algorithm?",
     [("A", "O(1)"), ("B", "O(n)"), ("C", "O(log n)"), ("D", "O(n²)")], "B", "Fundamentals of Programming"),
    ("Which programming construct allows conditional execution of code?",
     [("A", "Loop"), ("B", "Function"), ("C", "If-else statement"), ("D", "Array")], "C", "Fundamentals of Programming"),
    ("What will be the output of the following Python code: x = 10; print(x > 5 and x < 15)?",
     [("A", "True"), ("B", "False"), ("C", "10"), ("D", "Error")], "A", "Fundamentals of Programming"),
    ("Which of the following is NOT a primitive data type in C?",
     [("A", "int"), ("B", "float"), ("C", "string"), ("D", "char")], "C", "Fundamentals of Programming"),
    ("What is the purpose of modular programming?",
     [("A", "To increase code complexity"), ("B", "To break a program into smaller, manageable functions"),
      ("C", "To eliminate the need for debugging"), ("D", "To reduce program execution speed")], "B", "Fundamentals of Programming"),
    ("In a programming problem, you need to swap two variables without using a temporary variable. Which approach works in Python?",
     [("A", "a = a + b; b = a - b; a = a - b"), ("B", "a = b; b = a"),
      ("C", "a, b = b, a"), ("D", "swap(a, b)")], "C", "Fundamentals of Programming"),
    ("What is the primary advantage of using a linked list over an array?",
     [("A", "Faster access time"), ("B", "Dynamic size adjustment"),
      ("C", "Less memory usage"), ("D", "Constant-time insertion")], "B", "Data Structures"),
    ("Which data structure operates on a Last-In-First-Out (LIFO) principle?",
     [("A", "Queue"), ("B", "Stack"), ("C", "Linked List"), ("D", "Binary Tree")], "B", "Data Structures"),
    ("What is the worst-case time complexity of QuickSort?",
     [("A", "O(n log n)"), ("B", "O(n²)"), ("C", "O(n)"), ("D", "O(log n)")], "B", "Data Structures"),
    ("Which algorithm is used to find the shortest path in a weighted graph?",
     [("A", "Depth-First Search"), ("B", "Breadth-First Search"),
      ("C", "Dijkstra's Algorithm"), ("D", "Merge Sort")], "C", "Data Structures"),
    ("In a binary search tree, where are nodes with values less than the root stored?",
     [("A", "Right subtree"), ("B", "Left subtree"), ("C", "Parent node"), ("D", "Root node")], "B", "Data Structures"),
    ("What is the time complexity of inserting an element into a balanced binary search tree?",
     [("A", "O(1)"), ("B", "O(n)"), ("C", "O(log n)"), ("D", "O(n²)")], "C", "Data Structures"),
    ("Which OOP principle allows a class to inherit properties from another class?",
     [("A", "Encapsulation"), ("B", "Polymorphism"), ("C", "Inheritance"), ("D", "Abstraction")], "C", "Java / OOP"),
    ("What is the purpose of encapsulation in OOP?",
     [("A", "To allow multiple inheritance"), ("B", "To hide data and restrict direct access"),
      ("C", "To enable method overloading"), ("D", "To create abstract classes")], "B", "Java / OOP"),
    ("In Java, which keyword is used to refer to the current object?",
     [("A", "this"), ("B", "super"), ("C", "self"), ("D", "instance")], "A", "Java / OOP"),
    ("What will be the output of the following Java code?\nclass Animal { void sound() { System.out.println(\"Generic sound\"); } }\nclass Dog extends Animal { void sound() { System.out.println(\"Bark\"); } }\npublic class Main { public static void main(String[] args) { Animal a = new Dog(); a.sound(); } }",
     [("A", "Generic sound"), ("B", "Bark"), ("C", "Error"), ("D", "No output")], "B", "Java / OOP"),
    ("Which of the following is an example of polymorphism?",
     [("A", "Defining a variable"), ("B", "Overriding a method in a subclass"),
      ("C", "Declaring a constant"), ("D", "Creating a loop")], "B", "Java / OOP"),
    ("Which HTML tag is used to create a hyperlink?",
     [("A", "<link>"), ("B", "<a>"), ("C", "<href>"), ("D", "<url>")], "B", "Web Development"),
    ("What is the purpose of CSS in web development?",
     [("A", "To handle server-side logic"), ("B", "To style and format web pages"),
      ("C", "To manage databases"), ("D", "To execute JavaScript code")], "B", "Web Development"),
    ("Which JavaScript method is used to add an element to the end of an array?",
     [("A", "push()"), ("B", "pop()"), ("C", "shift()"), ("D", "unshift()")], "A", "Web Development"),
    ("What does AJAX stand for?",
     [("A", "Asynchronous JavaScript and XML"), ("B", "Active JavaScript and XML"),
      ("C", "Asynchronous JSON and XML"), ("D", "Automated JavaScript and XHTML")], "A", "Web Development"),
    ("Which HTTP method is used to retrieve data from a server?",
     [("A", "POST"), ("B", "GET"), ("C", "PUT"), ("D", "DELETE")], "B", "Web Development"),
    ("In a web application, where is JavaScript typically executed?",
     [("A", "Server-side"), ("B", "Client-side"), ("C", "Database"), ("D", "Middleware")], "B", "Web Development"),
    ("What is the output of the following JavaScript code?\nlet x = 5;\nconsole.log(x++ + ++x);",
     [("A", "10"), ("B", "11"), ("C", "12"), ("D", "13")], "C", "Web Development"),
    ("Which technology is commonly used for server-side scripting in web development?",
     [("A", "HTML"), ("B", "CSS"), ("C", "PHP"), ("D", "JavaScript")], "C", "Web Development"),
    ("What is the role of a web framework like Django?",
     [("A", "To manage database connections only"), ("B", "To provide a structure for developing web applications"),
      ("C", "To handle client-side styling"), ("D", "To execute SQL queries directly")], "B", "Web Development"),
    ("What is the primary programming language for Android app development?",
     [("A", "Swift"), ("B", "Java"), ("C", "Python"), ("D", "C++")], "B", "Android"),
    ("Which component in an Android application defines the user interface?",
     [("A", "Activity"), ("B", "Service"), ("C", "Broadcast Receiver"), ("D", "Content Provider")], "A", "Android"),
    ("What is the purpose of an Android Intent?",
     [("A", "To manage database connections"), ("B", "To facilitate communication between components"),
      ("C", "To handle background services"), ("D", "To secure the application")], "B", "Android"),
    ("Which file in an Android project specifies the app's permissions?",
     [("A", "AndroidManifest.xml"), ("B", "build.gradle"), ("C", "activity_main.xml"), ("D", "MainActivity.java")], "A", "Android"),
    ("What is a key security concern in mobile app development?",
     [("A", "Using too many colors in the UI"), ("B", "Storing sensitive data unencrypted"),
      ("C", "Including large images"), ("D", "Using multiple activities")], "B", "Android"),
    ("What is the purpose of a primary key in a database table?",
     [("A", "To allow duplicate records"), ("B", "To uniquely identify each record"),
      ("C", "To store foreign keys"), ("D", "To index all columns")], "B", "Database"),
    ("Which SQL statement is used to modify existing data in a table?",
     [("A", "INSERT"), ("B", "UPDATE"), ("C", "DELETE"), ("D", "SELECT")], "B", "Database"),
    ("What is the result of the following SQL query: SELECT * FROM Students WHERE Age > 20;?",
     [("A", "All records from Students"), ("B", "Records from Students where Age is greater than 20"),
      ("C", "Records from Students where Age is less than 20"), ("D", "No records")], "B", "Database"),
    ("What is normalization in database design?",
     [("A", "Adding redundant data to tables"), ("B", "Organizing data to eliminate redundancy"),
      ("C", "Creating multiple databases"), ("D", "Deleting unused tables")], "B", "Database"),
    ("Which type of relationship exists between two tables when a primary key in one table is linked to a foreign key in another?",
     [("A", "One-to-One"), ("B", "One-to-Many"), ("C", "Many-to-Many"), ("D", "No relationship")], "B", "Database"),
    ("What does ACID stand for in database systems?",
     [("A", "Atomicity, Consistency, Isolation, Durability"),
      ("B", "Accuracy, Completeness, Integrity, Dependability"),
      ("C", "Adaptability, Connectivity, Isolation, Durability"),
      ("D", "Atomicity, Consistency, Integration, Durability")], "A", "Database"),
    ("What is the primary function of an operating system?",
     [("A", "To write application code"), ("B", "To manage hardware and software resources"),
      ("C", "To design user interfaces"), ("D", "To compile programs")], "B", "Operating Systems"),
    ("Which scheduling algorithm selects the process with the shortest next CPU burst?",
     [("A", "First-Come, First-Served"), ("B", "Shortest Job Next"),
      ("C", "Round Robin"), ("D", "Priority Scheduling")], "B", "Operating Systems"),
    ("What is a deadlock in an operating system?",
     [("A", "A process running indefinitely"),
      ("B", "A situation where processes are unable to proceed due to resource conflicts"),
      ("C", "A memory overflow error"), ("D", "A hardware failure")], "B", "Operating Systems"),
    ("Which memory management technique divides memory into fixed-size partitions?",
     [("A", "Paging"), ("B", "Segmentation"), ("C", "Swapping"), ("D", "Fragmentation")], "A", "Operating Systems"),
    ("What is the purpose of a mutex in process synchronization?",
     [("A", "To allocate memory"), ("B", "To ensure mutual exclusion"),
      ("C", "To schedule processes"), ("D", "To manage I/O devices")], "B", "Operating Systems"),
    ("Which of the following is a security measure in modern operating systems?",
     [("A", "Allowing unrestricted access to all files"), ("B", "Implementing user authentication"),
      ("C", "Disabling firewalls"), ("D", "Storing passwords in plain text")], "B", "Operating Systems"),
    ("What is the primary goal of software engineering?",
     [("A", "To increase software complexity"), ("B", "To develop reliable and efficient software systems"),
      ("C", "To reduce software documentation"), ("D", "To eliminate testing")], "B", "Software Engineering"),
    ("Which software development model follows a linear and sequential approach?",
     [("A", "Agile"), ("B", "Waterfall"), ("C", "Spiral"), ("D", "Scrum")], "B", "Software Engineering"),
    ("What is a key characteristic of the Agile methodology?",
     [("A", "Fixed requirements throughout the project"), ("B", "Iterative and incremental development"),
      ("C", "No user involvement"), ("D", "Single-phase development")], "B", "Software Engineering"),
    ("Which diagram in UML represents the dynamic behavior of a system?",
     [("A", "Class Diagram"), ("B", "Use Case Diagram"), ("C", "Sequence Diagram"), ("D", "Component Diagram")], "C", "Software Engineering"),
    ("What is the purpose of a feasibility study in software engineering?",
     [("A", "To write code for the project"), ("B", "To assess the viability of a project"),
      ("C", "To deploy the software"), ("D", "To test the software")], "B", "Software Engineering"),
    ("Which of the following is a non-functional requirement?",
     [("A", "The system must allow users to log in"), ("B", "The system must respond within 2 seconds"),
      ("C", "The system must store user data"), ("D", "The system must generate reports")], "B", "Software Engineering"),
    ("What is the purpose of requirements elicitation?",
     [("A", "To test the software"), ("B", "To gather and document user needs"),
      ("C", "To deploy the system"), ("D", "To write code")], "B", "Software Engineering"),
    ("Which technique is commonly used to gather requirements from stakeholders?",
     [("A", "Writing code"), ("B", "Conducting interviews"), ("C", "Debugging software"), ("D", "Deploying the system")], "B", "Software Engineering"),
    ("What makes a requirement testable?",
     [("A", "It is vague and ambiguous"), ("B", "It is measurable and verifiable"),
      ("C", "It lacks clarity"), ("D", "It is incomplete")], "B", "Software Engineering"),
    ("Which document specifies both functional and non-functional requirements?",
     [("A", "Software Design Document"), ("B", "Software Requirements Specification (SRS)"),
      ("C", "Test Plan"), ("D", "User Manual")], "B", "Software Engineering"),
    ("What is a challenge in managing software requirements?",
     [("A", "Writing error-free code"), ("B", "Handling requirement changes during development"),
      ("C", "Deploying the software"), ("D", "Testing the user interface")], "B", "Software Engineering"),
    ("What is the role of software architecture in a system?",
     [("A", "To write detailed code"), ("B", "To define the system's structure and behavior"),
      ("C", "To test the software"), ("D", "To deploy the application")], "B", "Software Architecture"),
    ("Which design pattern separates an object's abstraction from its implementation?",
     [("A", "Singleton"), ("B", "Factory"), ("C", "Bridge"), ("D", "Observer")], "C", "Software Architecture"),
    ("Which architectural style is suitable for web-based applications?",
     [("A", "Monolithic"), ("B", "Client-Server"), ("C", "Pipe-and-Filter"), ("D", "Layered")], "B", "Software Architecture"),
    ("What is a quality attribute in software architecture?",
     [("A", "The programming language used"), ("B", "The system's performance or scalability"),
      ("C", "The number of developers"), ("D", "The project budget")], "B", "Software Architecture"),
    ("Which UML diagram is used to represent the structure of a system?",
     [("A", "Sequence Diagram"), ("B", "Class Diagram"), ("C", "Activity Diagram"), ("D", "Use Case Diagram")], "B", "Software Architecture"),
    ("What is the purpose of a Work Breakdown Structure (WBS)?",
     [("A", "To write code"), ("B", "To divide a project into manageable tasks"),
      ("C", "To test the software"), ("D", "To deploy the system")], "B", "Project Management"),
    ("Which project management tool is used to visualize task dependencies?",
     [("A", "Gantt Chart"), ("B", "Pie Chart"), ("C", "Histogram"), ("D", "Scatter Plot")], "A", "Project Management"),
    ("What is a key activity in risk management?",
     [("A", "Writing code"), ("B", "Identifying and mitigating potential risks"),
      ("C", "Designing the user interface"), ("D", "Testing the database")], "B", "Project Management"),
    ("In Scrum, who is responsible for prioritizing the product backlog?",
     [("A", "Scrum Master"), ("B", "Product Owner"), ("C", "Development Team"), ("D", "Stakeholders")], "B", "Project Management"),
    ("What is the purpose of a project schedule?",
     [("A", "To document code"), ("B", "To plan and track project timelines"),
      ("C", "To test the software"), ("D", "To manage hardware resources")], "B", "Project Management"),
    ("What is the purpose of unit testing?",
     [("A", "To test the entire system"), ("B", "To test individual components or functions"),
      ("C", "To test the user interface"), ("D", "To test the database")], "B", "Software Testing"),
    ("Which testing technique uses the internal structure of the code?",
     [("A", "Black-box testing"), ("B", "White-box testing"), ("C", "Integration testing"), ("D", "System testing")], "B", "Software Testing"),
    ("What is a test case?",
     [("A", "A set of conditions to verify a system's functionality"), ("B", "A programming script"),
      ("C", "A project plan"), ("D", "A database schema")], "A", "Software Testing"),
    ("What is a common goal of quality assurance in software development?",
     [("A", "To increase development time"), ("B", "To ensure the software meets specified requirements"),
      ("C", "To reduce documentation"), ("D", "To eliminate user feedback")], "B", "Software Testing"),
    ("Which of the following is a defect in software?",
     [("A", "A feature that meets user requirements"), ("B", "A bug that causes incorrect behavior"),
      ("C", "A well-documented code"), ("D", "A user manual")], "B", "Software Testing"),
    ("What is software maintenance?",
     [("A", "Writing new code from scratch"), ("B", "Updating and fixing existing software"),
      ("C", "Designing the user interface"), ("D", "Deploying the software")], "B", "Software Maintenance"),
    ("Which maintenance type addresses user-reported issues?",
     [("A", "Corrective maintenance"), ("B", "Adaptive maintenance"), ("C", "Perfective maintenance"), ("D", "Preventive maintenance")], "A", "Software Maintenance"),
    ("What is refactoring in software maintenance?",
     [("A", "Adding new features"), ("B", "Improving code structure without changing functionality"),
      ("C", "Deleting old code"), ("D", "Testing the software")], "B", "Software Maintenance"),
    ("Which factor affects software maintenance cost?",
     [("A", "The programming language used"), ("B", "The number of users"),
      ("C", "The complexity of the software"), ("D", "The project timeline")], "C", "Software Maintenance"),
    ("What is a benefit of applying best practices in software maintenance?",
     [("A", "Increased software bugs"), ("B", "Improved software reliability"),
      ("C", "Reduced documentation"), ("D", "Slower development")], "B", "Software Maintenance"),
    ("What is the purpose of the OSI model in networking?",
     [("A", "To write network protocols"), ("B", "To standardize network communication layers"),
      ("C", "To manage hardware resources"), ("D", "To secure the network")], "B", "Networking"),
    ("Which layer of the OSI model is responsible for routing?",
     [("A", "Data Link Layer"), ("B", "Network Layer"), ("C", "Transport Layer"), ("D", "Application Layer")], "B", "Networking"),
    ("What is the function of a router in a network?",
     [("A", "To connect devices within the same network"), ("B", "To forward data packets between networks"),
      ("C", "To store data packets"), ("D", "To encrypt data")], "B", "Networking"),
    ("Which protocol is used for secure web communication?",
     [("A", "HTTP"), ("B", "FTP"), ("C", "HTTPS"), ("D", "SMTP")], "C", "Networking"),
    ("What is a subnet mask used for?",
     [("A", "To encrypt network traffic"), ("B", "To divide a network into smaller subnetworks"),
      ("C", "To assign IP addresses"), ("D", "To secure the network")], "B", "Networking"),
    ("Which device is used to connect different network types?",
     [("A", "Switch"), ("B", "Hub"), ("C", "Gateway"), ("D", "Repeater")], "C", "Networking"),
    ("What is the purpose of encryption in software security?",
     [("A", "To increase software size"), ("B", "To protect data confidentiality"),
      ("C", "To speed up execution"), ("D", "To simplify code")], "B", "Security"),
    ("Which type of attack involves injecting malicious code into a web application?",
     [("A", "Phishing"), ("B", "SQL Injection"), ("C", "Denial of Service"), ("D", "Brute Force")], "B", "Security"),
    ("What is a firewall used for in a network?",
     [("A", "To store data"), ("B", "To monitor and control network traffic"),
      ("C", "To assign IP addresses"), ("D", "To manage databases")], "B", "Security"),
    ("Which authentication method verifies a user's identity using multiple factors?",
     [("A", "Single Sign-On"), ("B", "Multi-Factor Authentication"),
      ("C", "Password Authentication"), ("D", "Token Authentication")], "B", "Security"),
    ("What is a common way to mitigate software vulnerabilities?",
     [("A", "Ignoring user feedback"), ("B", "Applying regular security patches"),
      ("C", "Increasing code complexity"), ("D", "Disabling encryption")], "B", "Security"),
    ("What is an intelligent agent in AI?",
     [("A", "A program that writes code"), ("B", "A system that perceives and acts in an environment"),
      ("C", "A database management system"), ("D", "A user interface")], "B", "AI / ML"),
    ("Which search strategy explores all nodes at the current depth before moving deeper?",
     [("A", "Depth-First Search"), ("B", "Breadth-First Search"),
      ("C", "A* Search"), ("D", "Greedy Search")], "B", "AI / ML"),
    ("What is the purpose of a knowledge base in an expert system?",
     [("A", "To store user data"), ("B", "To store rules and facts for decision-making"),
      ("C", "To manage hardware resources"), ("D", "To execute search algorithms")], "B", "AI / ML"),
    ("Which AI technique mimics human reasoning using if-then rules?",
     [("A", "Machine Learning"), ("B", "Expert Systems"), ("C", "Neural Networks"), ("D", "Genetic Algorithms")], "B", "AI / ML"),
    ("What is a benefit of lifelong learning in AI?",
     [("A", "Reduced system performance"), ("B", "Continuous adaptation to new data"),
      ("C", "Increased code complexity"), ("D", "Limited application scope")], "B", "AI / ML"),
    ("What is the main difference between supervised and unsupervised learning?",
     [("A", "Supervised learning uses labeled data, unsupervised does not"),
      ("B", "Unsupervised learning uses labeled data, supervised does not"),
      ("C", "Supervised learning is faster than unsupervised"), ("D", "Unsupervised learning requires more data")], "A", "AI / ML"),
    ("Which algorithm is commonly used for classification tasks in machine learning?",
     [("A", "K-Means Clustering"), ("B", "Linear Regression"), ("C", "Decision Trees"), ("D", "Principal Component Analysis")], "C", "AI / ML"),
    ("What is overfitting in machine learning?",
     [("A", "When a model performs well on new data"),
      ("B", "When a model is too complex and fits noise in the training data"),
      ("C", "When a model is too simple"), ("D", "When a model fails to train")], "B", "AI / ML"),
    ("Which of the following is a supervised learning task?",
     [("A", "Clustering customer data"), ("B", "Predicting house prices based on features"),
      ("C", "Reducing data dimensions"), ("D", "Finding patterns in unlabeled data")], "B", "AI / ML"),
    ("What is the purpose of a training dataset in machine learning?",
     [("A", "To test the model's performance"), ("B", "To train the model to learn patterns"),
      ("C", "To validate the model"), ("D", "To deploy the model")], "B", "AI / ML"),
]

assert len(RAW) == 100, f"Expected 100 questions, got {len(RAW)}"
